# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialog_tool_analysis.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_analysis(object):
    def setupUi(self, Dialog_analysis):
        Dialog_analysis.setObjectName(_fromUtf8("Dialog_analysis"))
        Dialog_analysis.resize(1009, 1008)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_analysis.sizePolicy().hasHeightForWidth())
        Dialog_analysis.setSizePolicy(sizePolicy)
        Dialog_analysis.setStyleSheet(_fromUtf8("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog_analysis)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(Dialog_analysis)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 974, 1262))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.radioButton_analysis_single = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_analysis_single.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_analysis_single.setChecked(True)
        self.radioButton_analysis_single.setObjectName(_fromUtf8("radioButton_analysis_single"))
        self.gridLayout_12.addWidget(self.radioButton_analysis_single, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(260, 48, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 1, 2, 1)
        self.radioButton_analysis_batch = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_analysis_batch.setChecked(False)
        self.radioButton_analysis_batch.setObjectName(_fromUtf8("radioButton_analysis_batch"))
        self.gridLayout_12.addWidget(self.radioButton_analysis_batch, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(260, 45, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 4, 2, 1)
        spacerItem2 = QtGui.QSpacerItem(17, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem2, 1, 0, 1, 1)
        self.pushButton_analysis_batch_choose_folder = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_analysis_batch_choose_folder.setObjectName(_fromUtf8("pushButton_analysis_batch_choose_folder"))
        self.gridLayout_12.addWidget(self.pushButton_analysis_batch_choose_folder, 1, 2, 1, 1)
        self.lineEdit_analysis_folder_name = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_analysis_folder_name.setEnabled(False)
        self.lineEdit_analysis_folder_name.setInputMask(_fromUtf8(""))
        self.lineEdit_analysis_folder_name.setText(_fromUtf8(""))
        self.lineEdit_analysis_folder_name.setFrame(False)
        self.lineEdit_analysis_folder_name.setReadOnly(True)
        self.lineEdit_analysis_folder_name.setObjectName(_fromUtf8("lineEdit_analysis_folder_name"))
        self.gridLayout_12.addWidget(self.lineEdit_analysis_folder_name, 1, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_analysis_nlp = QtGui.QGroupBox(self.groupBox)
        self.groupBox_analysis_nlp.setFlat(False)
        self.groupBox_analysis_nlp.setCheckable(True)
        self.groupBox_analysis_nlp.setChecked(False)
        self.groupBox_analysis_nlp.setObjectName(_fromUtf8("groupBox_analysis_nlp"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_analysis_nlp)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_3.addWidget(self.groupBox_analysis_nlp)
        self.groupBox_analysis_convex_hull = QtGui.QGroupBox(self.groupBox)
        self.groupBox_analysis_convex_hull.setFlat(False)
        self.groupBox_analysis_convex_hull.setCheckable(True)
        self.groupBox_analysis_convex_hull.setChecked(False)
        self.groupBox_analysis_convex_hull.setObjectName(_fromUtf8("groupBox_analysis_convex_hull"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_analysis_convex_hull)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout_3.addWidget(self.groupBox_analysis_convex_hull)
        self.groupBox_analysis_quality_control = QtGui.QGroupBox(self.groupBox)
        self.groupBox_analysis_quality_control.setFlat(True)
        self.groupBox_analysis_quality_control.setCheckable(True)
        self.groupBox_analysis_quality_control.setChecked(False)
        self.groupBox_analysis_quality_control.setObjectName(_fromUtf8("groupBox_analysis_quality_control"))
        self.verticalLayout_3.addWidget(self.groupBox_analysis_quality_control)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_analysis_dbscan = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_analysis_dbscan.setFlat(False)
        self.groupBox_analysis_dbscan.setCheckable(True)
        self.groupBox_analysis_dbscan.setChecked(False)
        self.groupBox_analysis_dbscan.setObjectName(_fromUtf8("groupBox_analysis_dbscan"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_analysis_dbscan)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.line_2 = QtGui.QFrame(self.groupBox_analysis_dbscan)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_4.addWidget(self.line_2, 0, 6, 2, 2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 9, 2, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_analysis_dbscan)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)
        self.spinBox_analysis_dbscan_eps = QtGui.QSpinBox(self.groupBox_analysis_dbscan)
        self.spinBox_analysis_dbscan_eps.setMinimum(1)
        self.spinBox_analysis_dbscan_eps.setMaximum(20000)
        self.spinBox_analysis_dbscan_eps.setSingleStep(10)
        self.spinBox_analysis_dbscan_eps.setProperty("value", 100)
        self.spinBox_analysis_dbscan_eps.setObjectName(_fromUtf8("spinBox_analysis_dbscan_eps"))
        self.gridLayout_4.addWidget(self.spinBox_analysis_dbscan_eps, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_analysis_dbscan)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 1, 1, 1)
        self.spinBox_analysis_dbscan_minn = QtGui.QSpinBox(self.groupBox_analysis_dbscan)
        self.spinBox_analysis_dbscan_minn.setMinimum(1)
        self.spinBox_analysis_dbscan_minn.setMaximum(1000)
        self.spinBox_analysis_dbscan_minn.setProperty("value", 3)
        self.spinBox_analysis_dbscan_minn.setObjectName(_fromUtf8("spinBox_analysis_dbscan_minn"))
        self.gridLayout_4.addWidget(self.spinBox_analysis_dbscan_minn, 1, 3, 1, 1)
        self.checkBox_analysis_dbscan_save_all = QtGui.QCheckBox(self.groupBox_analysis_dbscan)
        self.checkBox_analysis_dbscan_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_dbscan_save_all.setObjectName(_fromUtf8("checkBox_analysis_dbscan_save_all"))
        self.gridLayout_4.addWidget(self.checkBox_analysis_dbscan_save_all, 0, 11, 1, 1)
        self.checkBox_analysis_dbscan_export_pdb = QtGui.QCheckBox(self.groupBox_analysis_dbscan)
        self.checkBox_analysis_dbscan_export_pdb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_dbscan_export_pdb.setObjectName(_fromUtf8("checkBox_analysis_dbscan_export_pdb"))
        self.gridLayout_4.addWidget(self.checkBox_analysis_dbscan_export_pdb, 1, 11, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_analysis_dbscan)
        self.groupBox_analysis_bayesian = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_analysis_bayesian.setCheckable(True)
        self.groupBox_analysis_bayesian.setChecked(False)
        self.groupBox_analysis_bayesian.setObjectName(_fromUtf8("groupBox_analysis_bayesian"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_analysis_bayesian)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_analysis_bayesian_rseqminlabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        self.label_analysis_bayesian_rseqminlabel.setObjectName(_fromUtf8("label_analysis_bayesian_rseqminlabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_rseqminlabel, 0, 0, 1, 1)
        self.spinBox_analysis_bayesian_rseqmin = QtGui.QSpinBox(self.groupBox_analysis_bayesian)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_analysis_bayesian_rseqmin.sizePolicy().hasHeightForWidth())
        self.spinBox_analysis_bayesian_rseqmin.setSizePolicy(sizePolicy)
        self.spinBox_analysis_bayesian_rseqmin.setMinimum(10)
        self.spinBox_analysis_bayesian_rseqmin.setMaximum(500)
        self.spinBox_analysis_bayesian_rseqmin.setProperty("value", 30)
        self.spinBox_analysis_bayesian_rseqmin.setObjectName(_fromUtf8("spinBox_analysis_bayesian_rseqmin"))
        self.gridLayout_10.addWidget(self.spinBox_analysis_bayesian_rseqmin, 0, 1, 1, 2)
        self.line_4 = QtGui.QFrame(self.groupBox_analysis_bayesian)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_10.addWidget(self.line_4, 0, 3, 2, 1)
        self.label_analysis_bayesian_rseqmaxlabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_analysis_bayesian_rseqmaxlabel.sizePolicy().hasHeightForWidth())
        self.label_analysis_bayesian_rseqmaxlabel.setSizePolicy(sizePolicy)
        self.label_analysis_bayesian_rseqmaxlabel.setObjectName(_fromUtf8("label_analysis_bayesian_rseqmaxlabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_rseqmaxlabel, 0, 4, 1, 2)
        self.spinBox_analysis_bayesian_rseqmax = QtGui.QSpinBox(self.groupBox_analysis_bayesian)
        self.spinBox_analysis_bayesian_rseqmax.setMinimum(10)
        self.spinBox_analysis_bayesian_rseqmax.setMaximum(500)
        self.spinBox_analysis_bayesian_rseqmax.setProperty("value", 200)
        self.spinBox_analysis_bayesian_rseqmax.setObjectName(_fromUtf8("spinBox_analysis_bayesian_rseqmax"))
        self.gridLayout_10.addWidget(self.spinBox_analysis_bayesian_rseqmax, 0, 6, 1, 1)
        self.line_5 = QtGui.QFrame(self.groupBox_analysis_bayesian)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_10.addWidget(self.line_5, 0, 7, 2, 1)
        self.label_analysis_bayesian_rseqdifflabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        self.label_analysis_bayesian_rseqdifflabel.setObjectName(_fromUtf8("label_analysis_bayesian_rseqdifflabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_rseqdifflabel, 0, 8, 1, 1)
        self.spinBox_analysis_bayesian_rseqdiff = QtGui.QSpinBox(self.groupBox_analysis_bayesian)
        self.spinBox_analysis_bayesian_rseqdiff.setMinimum(1)
        self.spinBox_analysis_bayesian_rseqdiff.setMaximum(5000)
        self.spinBox_analysis_bayesian_rseqdiff.setProperty("value", 10)
        self.spinBox_analysis_bayesian_rseqdiff.setObjectName(_fromUtf8("spinBox_analysis_bayesian_rseqdiff"))
        self.gridLayout_10.addWidget(self.spinBox_analysis_bayesian_rseqdiff, 0, 9, 1, 1)
        self.line_8 = QtGui.QFrame(self.groupBox_analysis_bayesian)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_10.addWidget(self.line_8, 0, 10, 2, 1)
        self.label_analysis_bayesian_alphalabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        self.label_analysis_bayesian_alphalabel.setObjectName(_fromUtf8("label_analysis_bayesian_alphalabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_alphalabel, 0, 11, 1, 1)
        self.spinBox_analysis_bayesian_alpha = QtGui.QSpinBox(self.groupBox_analysis_bayesian)
        self.spinBox_analysis_bayesian_alpha.setMaximum(100000)
        self.spinBox_analysis_bayesian_alpha.setProperty("value", 20)
        self.spinBox_analysis_bayesian_alpha.setObjectName(_fromUtf8("spinBox_analysis_bayesian_alpha"))
        self.gridLayout_10.addWidget(self.spinBox_analysis_bayesian_alpha, 0, 12, 1, 1)
        self.line_9 = QtGui.QFrame(self.groupBox_analysis_bayesian)
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_10.addWidget(self.line_9, 0, 13, 2, 1)
        self.checkBox_analysis_bayesian_save_all = QtGui.QCheckBox(self.groupBox_analysis_bayesian)
        self.checkBox_analysis_bayesian_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_bayesian_save_all.setObjectName(_fromUtf8("checkBox_analysis_bayesian_save_all"))
        self.gridLayout_10.addWidget(self.checkBox_analysis_bayesian_save_all, 0, 14, 1, 1)
        self.label_analysis_bayesian_thseqminlabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        self.label_analysis_bayesian_thseqminlabel.setObjectName(_fromUtf8("label_analysis_bayesian_thseqminlabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_thseqminlabel, 1, 0, 1, 1)
        self.spinBox_analysis_bayesian_thseqmin = QtGui.QSpinBox(self.groupBox_analysis_bayesian)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_analysis_bayesian_thseqmin.sizePolicy().hasHeightForWidth())
        self.spinBox_analysis_bayesian_thseqmin.setSizePolicy(sizePolicy)
        self.spinBox_analysis_bayesian_thseqmin.setMinimum(5)
        self.spinBox_analysis_bayesian_thseqmin.setMaximum(5000)
        self.spinBox_analysis_bayesian_thseqmin.setProperty("value", 10)
        self.spinBox_analysis_bayesian_thseqmin.setObjectName(_fromUtf8("spinBox_analysis_bayesian_thseqmin"))
        self.gridLayout_10.addWidget(self.spinBox_analysis_bayesian_thseqmin, 1, 1, 1, 2)
        self.label_analysis_bayesian_thseqmaxlabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        self.label_analysis_bayesian_thseqmaxlabel.setObjectName(_fromUtf8("label_analysis_bayesian_thseqmaxlabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_thseqmaxlabel, 1, 4, 1, 2)
        self.spinBox_analysis_bayesian_thseqmax = QtGui.QSpinBox(self.groupBox_analysis_bayesian)
        self.spinBox_analysis_bayesian_thseqmax.setMinimum(5)
        self.spinBox_analysis_bayesian_thseqmax.setMaximum(5000)
        self.spinBox_analysis_bayesian_thseqmax.setProperty("value", 500)
        self.spinBox_analysis_bayesian_thseqmax.setObjectName(_fromUtf8("spinBox_analysis_bayesian_thseqmax"))
        self.gridLayout_10.addWidget(self.spinBox_analysis_bayesian_thseqmax, 1, 6, 1, 1)
        self.label_analysis_bayesian_thseqdifflabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        self.label_analysis_bayesian_thseqdifflabel.setObjectName(_fromUtf8("label_analysis_bayesian_thseqdifflabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_thseqdifflabel, 1, 8, 1, 1)
        self.spinBox_analysis_bayesian_thseqdiff = QtGui.QSpinBox(self.groupBox_analysis_bayesian)
        self.spinBox_analysis_bayesian_thseqdiff.setMinimum(5)
        self.spinBox_analysis_bayesian_thseqdiff.setMaximum(5000)
        self.spinBox_analysis_bayesian_thseqdiff.setProperty("value", 10)
        self.spinBox_analysis_bayesian_thseqdiff.setObjectName(_fromUtf8("spinBox_analysis_bayesian_thseqdiff"))
        self.gridLayout_10.addWidget(self.spinBox_analysis_bayesian_thseqdiff, 1, 9, 1, 1)
        self.label_analysis_bayesian_pbackgroundlabel = QtGui.QLabel(self.groupBox_analysis_bayesian)
        self.label_analysis_bayesian_pbackgroundlabel.setObjectName(_fromUtf8("label_analysis_bayesian_pbackgroundlabel"))
        self.gridLayout_10.addWidget(self.label_analysis_bayesian_pbackgroundlabel, 1, 11, 1, 1)
        self.doubleSpinBox_analysis_bayesian_pbackground = QtGui.QDoubleSpinBox(self.groupBox_analysis_bayesian)
        self.doubleSpinBox_analysis_bayesian_pbackground.setMaximum(1.0)
        self.doubleSpinBox_analysis_bayesian_pbackground.setSingleStep(0.01)
        self.doubleSpinBox_analysis_bayesian_pbackground.setProperty("value", 0.5)
        self.doubleSpinBox_analysis_bayesian_pbackground.setObjectName(_fromUtf8("doubleSpinBox_analysis_bayesian_pbackground"))
        self.gridLayout_10.addWidget(self.doubleSpinBox_analysis_bayesian_pbackground, 1, 12, 1, 1)
        self.checkBox_analysis_bayesian_usehistogram = QtGui.QCheckBox(self.groupBox_analysis_bayesian)
        self.checkBox_analysis_bayesian_usehistogram.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_analysis_bayesian_usehistogram.setTristate(False)
        self.checkBox_analysis_bayesian_usehistogram.setObjectName(_fromUtf8("checkBox_analysis_bayesian_usehistogram"))
        self.gridLayout_10.addWidget(self.checkBox_analysis_bayesian_usehistogram, 2, 0, 1, 2)
        self.pushButton_analysis_bayesian_choose_file = QtGui.QPushButton(self.groupBox_analysis_bayesian)
        self.pushButton_analysis_bayesian_choose_file.setEnabled(True)
        self.pushButton_analysis_bayesian_choose_file.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_analysis_bayesian_choose_file.setMouseTracking(False)
        self.pushButton_analysis_bayesian_choose_file.setCheckable(False)
        self.pushButton_analysis_bayesian_choose_file.setObjectName(_fromUtf8("pushButton_analysis_bayesian_choose_file"))
        self.gridLayout_10.addWidget(self.pushButton_analysis_bayesian_choose_file, 2, 2, 1, 3)
        self.lineEdit_analysis_bayesian_histogramlinedit = QtGui.QLineEdit(self.groupBox_analysis_bayesian)
        self.lineEdit_analysis_bayesian_histogramlinedit.setEnabled(False)
        self.lineEdit_analysis_bayesian_histogramlinedit.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_analysis_bayesian_histogramlinedit.setFont(font)
        self.lineEdit_analysis_bayesian_histogramlinedit.setFrame(False)
        self.lineEdit_analysis_bayesian_histogramlinedit.setReadOnly(True)
        self.lineEdit_analysis_bayesian_histogramlinedit.setObjectName(_fromUtf8("lineEdit_analysis_bayesian_histogramlinedit"))
        self.gridLayout_10.addWidget(self.lineEdit_analysis_bayesian_histogramlinedit, 2, 5, 1, 5)
        self.verticalLayout.addWidget(self.groupBox_analysis_bayesian)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_analysis_internalization_surface = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_analysis_internalization_surface.setFlat(False)
        self.groupBox_analysis_internalization_surface.setCheckable(True)
        self.groupBox_analysis_internalization_surface.setChecked(False)
        self.groupBox_analysis_internalization_surface.setObjectName(_fromUtf8("groupBox_analysis_internalization_surface"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_analysis_internalization_surface)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.line_3 = QtGui.QFrame(self.groupBox_analysis_internalization_surface)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_5.addWidget(self.line_3, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 6, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_analysis_internalization_surface)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 3, 1, 1)
        self.spinBox_analysis_internalization_surface_treshold = QtGui.QSpinBox(self.groupBox_analysis_internalization_surface)
        self.spinBox_analysis_internalization_surface_treshold.setMaximum(10000)
        self.spinBox_analysis_internalization_surface_treshold.setSingleStep(10)
        self.spinBox_analysis_internalization_surface_treshold.setProperty("value", 100)
        self.spinBox_analysis_internalization_surface_treshold.setObjectName(_fromUtf8("spinBox_analysis_internalization_surface_treshold"))
        self.gridLayout_5.addWidget(self.spinBox_analysis_internalization_surface_treshold, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_analysis_internalization_surface)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_analysis_internalization_surface_channel_convex = QtGui.QComboBox(self.groupBox_analysis_internalization_surface)
        self.comboBox_analysis_internalization_surface_channel_convex.setObjectName(_fromUtf8("comboBox_analysis_internalization_surface_channel_convex"))
        self.gridLayout_5.addWidget(self.comboBox_analysis_internalization_surface_channel_convex, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_analysis_internalization_surface)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.comboBox_analysis_internalization_surface_channel_distance = QtGui.QComboBox(self.groupBox_analysis_internalization_surface)
        self.comboBox_analysis_internalization_surface_channel_distance.setObjectName(_fromUtf8("comboBox_analysis_internalization_surface_channel_distance"))
        self.gridLayout_5.addWidget(self.comboBox_analysis_internalization_surface_channel_distance, 0, 1, 1, 1)
        self.checkBox_analysis_internalization_surface_save_all = QtGui.QCheckBox(self.groupBox_analysis_internalization_surface)
        self.checkBox_analysis_internalization_surface_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_internalization_surface_save_all.setObjectName(_fromUtf8("checkBox_analysis_internalization_surface_save_all"))
        self.gridLayout_5.addWidget(self.checkBox_analysis_internalization_surface_save_all, 0, 7, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_analysis_internalization_surface)
        self.groupBox_analysis_internalization_dr = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_analysis_internalization_dr.setFlat(False)
        self.groupBox_analysis_internalization_dr.setCheckable(True)
        self.groupBox_analysis_internalization_dr.setChecked(False)
        self.groupBox_analysis_internalization_dr.setObjectName(_fromUtf8("groupBox_analysis_internalization_dr"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_analysis_internalization_dr)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox_analysis_internalization_dr_channel_distance = QtGui.QComboBox(self.groupBox_analysis_internalization_dr)
        self.comboBox_analysis_internalization_dr_channel_distance.setObjectName(_fromUtf8("comboBox_analysis_internalization_dr_channel_distance"))
        self.gridLayout_7.addWidget(self.comboBox_analysis_internalization_dr_channel_distance, 0, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_analysis_internalization_dr)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 0, 2, 1, 1)
        self.checkBox_analysis_internalization_dr_save_all = QtGui.QCheckBox(self.groupBox_analysis_internalization_dr)
        self.checkBox_analysis_internalization_dr_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_internalization_dr_save_all.setObjectName(_fromUtf8("checkBox_analysis_internalization_dr_save_all"))
        self.gridLayout_7.addWidget(self.checkBox_analysis_internalization_dr_save_all, 0, 3, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_analysis_internalization_dr)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setChecked(False)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_analysis_euclidean_within = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_analysis_euclidean_within.setFlat(False)
        self.groupBox_analysis_euclidean_within.setCheckable(True)
        self.groupBox_analysis_euclidean_within.setChecked(False)
        self.groupBox_analysis_euclidean_within.setObjectName(_fromUtf8("groupBox_analysis_euclidean_within"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_analysis_euclidean_within)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 0, 1, 1)
        self.checkBox_analysis_euclidean_within_save_all = QtGui.QCheckBox(self.groupBox_analysis_euclidean_within)
        self.checkBox_analysis_euclidean_within_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_within_save_all.setObjectName(_fromUtf8("checkBox_analysis_euclidean_within_save_all"))
        self.gridLayout_6.addWidget(self.checkBox_analysis_euclidean_within_save_all, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_analysis_euclidean_within)
        self.groupBox_analysis_euclidean_between = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_analysis_euclidean_between.setFlat(False)
        self.groupBox_analysis_euclidean_between.setCheckable(True)
        self.groupBox_analysis_euclidean_between.setChecked(False)
        self.groupBox_analysis_euclidean_between.setObjectName(_fromUtf8("groupBox_analysis_euclidean_between"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_analysis_euclidean_between)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_analysis_euclidean_between)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_analysis_euclidean_between_channel_minimum_dist = QtGui.QComboBox(self.groupBox_analysis_euclidean_between)
        self.comboBox_analysis_euclidean_between_channel_minimum_dist.setObjectName(_fromUtf8("comboBox_analysis_euclidean_between_channel_minimum_dist"))
        self.gridLayout_3.addWidget(self.comboBox_analysis_euclidean_between_channel_minimum_dist, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_analysis_euclidean_between)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.comboBox_analysis_euclidean_between_channel_from = QtGui.QComboBox(self.groupBox_analysis_euclidean_between)
        self.comboBox_analysis_euclidean_between_channel_from.setObjectName(_fromUtf8("comboBox_analysis_euclidean_between_channel_from"))
        self.gridLayout_3.addWidget(self.comboBox_analysis_euclidean_between_channel_from, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.groupBox_analysis_euclidean_between_confocal = QtGui.QGroupBox(self.groupBox_analysis_euclidean_between)
        self.groupBox_analysis_euclidean_between_confocal.setFlat(True)
        self.groupBox_analysis_euclidean_between_confocal.setCheckable(True)
        self.groupBox_analysis_euclidean_between_confocal.setChecked(False)
        self.groupBox_analysis_euclidean_between_confocal.setObjectName(_fromUtf8("groupBox_analysis_euclidean_between_confocal"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_analysis_euclidean_between_confocal)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_analysis_euclidean_between_channel_from_confocal = QtGui.QComboBox(self.groupBox_analysis_euclidean_between_confocal)
        self.comboBox_analysis_euclidean_between_channel_from_confocal.setObjectName(_fromUtf8("comboBox_analysis_euclidean_between_channel_from_confocal"))
        self.horizontalLayout_2.addWidget(self.comboBox_analysis_euclidean_between_channel_from_confocal)
        self.label_2 = QtGui.QLabel(self.groupBox_analysis_euclidean_between_confocal)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold = QtGui.QSpinBox(self.groupBox_analysis_euclidean_between_confocal)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold.setMaximum(100)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold.setProperty("value", 10)
        self.spinBox_analysis_euclidean_between_channel_peak_threshold.setObjectName(_fromUtf8("spinBox_analysis_euclidean_between_channel_peak_threshold"))
        self.horizontalLayout_2.addWidget(self.spinBox_analysis_euclidean_between_channel_peak_threshold)
        self.label_23 = QtGui.QLabel(self.groupBox_analysis_euclidean_between_confocal)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_2.addWidget(self.label_23)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold = QtGui.QSpinBox(self.groupBox_analysis_euclidean_between_confocal)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setMinimum(1)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setMaximum(1000)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setSingleStep(10)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setProperty("value", 100)
        self.spinBox_analysis_euclidean_between_channel_distance_threshold.setObjectName(_fromUtf8("spinBox_analysis_euclidean_between_channel_distance_threshold"))
        self.horizontalLayout_2.addWidget(self.spinBox_analysis_euclidean_between_channel_distance_threshold)
        self.label_24 = QtGui.QLabel(self.groupBox_analysis_euclidean_between_confocal)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_2.addWidget(self.label_24)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold = QtGui.QSpinBox(self.groupBox_analysis_euclidean_between_confocal)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold.setMaximum(100)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold.setProperty("value", 20)
        self.spinBox_analysis_euclidean_between_channel_pixel_threshold.setObjectName(_fromUtf8("spinBox_analysis_euclidean_between_channel_pixel_threshold"))
        self.horizontalLayout_2.addWidget(self.spinBox_analysis_euclidean_between_channel_pixel_threshold)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.groupBox_analysis_euclidean_between_confocal)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.checkBox_analysis_euclidean_between_save_all = QtGui.QCheckBox(self.groupBox_analysis_euclidean_between)
        self.checkBox_analysis_euclidean_between_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_between_save_all.setObjectName(_fromUtf8("checkBox_analysis_euclidean_between_save_all"))
        self.horizontalLayout_3.addWidget(self.checkBox_analysis_euclidean_between_save_all)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_analysis_euclidean_between)
        self.groupBox_analysis_euclidean_surface_between = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_analysis_euclidean_surface_between.setFlat(False)
        self.groupBox_analysis_euclidean_surface_between.setCheckable(True)
        self.groupBox_analysis_euclidean_surface_between.setChecked(False)
        self.groupBox_analysis_euclidean_surface_between.setObjectName(_fromUtf8("groupBox_analysis_euclidean_surface_between"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_analysis_euclidean_surface_between)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_13 = QtGui.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.comboBox_analysis_euclidean_surface_between_channel_reference = QtGui.QComboBox(self.groupBox_analysis_euclidean_surface_between)
        self.comboBox_analysis_euclidean_surface_between_channel_reference.setObjectName(_fromUtf8("comboBox_analysis_euclidean_surface_between_channel_reference"))
        self.gridLayout_2.addWidget(self.comboBox_analysis_euclidean_surface_between_channel_reference, 1, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 5, 1, 1)
        self.comboBox_analysis_euclidean_surface_between_channel_convex = QtGui.QComboBox(self.groupBox_analysis_euclidean_surface_between)
        self.comboBox_analysis_euclidean_surface_between_channel_convex.setObjectName(_fromUtf8("comboBox_analysis_euclidean_surface_between_channel_convex"))
        self.gridLayout_2.addWidget(self.comboBox_analysis_euclidean_surface_between_channel_convex, 0, 1, 1, 1)
        self.comboBox_analysis_euclidean_surface_between_channel_distance = QtGui.QComboBox(self.groupBox_analysis_euclidean_surface_between)
        self.comboBox_analysis_euclidean_surface_between_channel_distance.setObjectName(_fromUtf8("comboBox_analysis_euclidean_surface_between_channel_distance"))
        self.gridLayout_2.addWidget(self.comboBox_analysis_euclidean_surface_between_channel_distance, 2, 1, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_analysis_euclidean_surface_between)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.spinBox_analysis_euclidean_surface_between_distance_limit = QtGui.QSpinBox(self.groupBox_analysis_euclidean_surface_between)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setMinimum(1)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setMaximum(1000)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setSingleStep(10)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setProperty("value", 100)
        self.spinBox_analysis_euclidean_surface_between_distance_limit.setObjectName(_fromUtf8("spinBox_analysis_euclidean_surface_between_distance_limit"))
        self.gridLayout_2.addWidget(self.spinBox_analysis_euclidean_surface_between_distance_limit, 0, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_analysis_euclidean_surface_between)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.checkBox_analysis_euclidean_surface_between_save_all = QtGui.QCheckBox(self.groupBox_analysis_euclidean_surface_between)
        self.checkBox_analysis_euclidean_surface_between_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_surface_between_save_all.setObjectName(_fromUtf8("checkBox_analysis_euclidean_surface_between_save_all"))
        self.gridLayout_2.addWidget(self.checkBox_analysis_euclidean_surface_between_save_all, 0, 7, 1, 1)
        self.checkBox_analysis_euclidean_surface_between_export_pdb = QtGui.QCheckBox(self.groupBox_analysis_euclidean_surface_between)
        self.checkBox_analysis_euclidean_surface_between_export_pdb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_euclidean_surface_between_export_pdb.setObjectName(_fromUtf8("checkBox_analysis_euclidean_surface_between_export_pdb"))
        self.gridLayout_2.addWidget(self.checkBox_analysis_euclidean_surface_between_export_pdb, 1, 7, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_analysis_euclidean_surface_between)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.groupBox_13 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_13.setFlat(False)
        self.groupBox_13.setCheckable(False)
        self.groupBox_13.setChecked(False)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.groupBox_analysis_surface_density = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_analysis_surface_density.setFlat(False)
        self.groupBox_analysis_surface_density.setCheckable(True)
        self.groupBox_analysis_surface_density.setChecked(False)
        self.groupBox_analysis_surface_density.setObjectName(_fromUtf8("groupBox_analysis_surface_density"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_analysis_surface_density)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_analysis_surface_density_channel_convex = QtGui.QComboBox(self.groupBox_analysis_surface_density)
        self.comboBox_analysis_surface_density_channel_convex.setObjectName(_fromUtf8("comboBox_analysis_surface_density_channel_convex"))
        self.gridLayout.addWidget(self.comboBox_analysis_surface_density_channel_convex, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_analysis_surface_density)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.line_6 = QtGui.QFrame(self.groupBox_analysis_surface_density)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_analysis_surface_density)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.comboBox_analysis_surface_density_channel_density = QtGui.QComboBox(self.groupBox_analysis_surface_density)
        self.comboBox_analysis_surface_density_channel_density.setObjectName(_fromUtf8("comboBox_analysis_surface_density_channel_density"))
        self.gridLayout.addWidget(self.comboBox_analysis_surface_density_channel_density, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_analysis_surface_density)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_analysis_surface_density)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 1, 3, 1, 1)
        self.spinBox_analysis_surface_density_treshold = QtGui.QSpinBox(self.groupBox_analysis_surface_density)
        self.spinBox_analysis_surface_density_treshold.setMinimum(1)
        self.spinBox_analysis_surface_density_treshold.setMaximum(1000)
        self.spinBox_analysis_surface_density_treshold.setProperty("value", 80)
        self.spinBox_analysis_surface_density_treshold.setObjectName(_fromUtf8("spinBox_analysis_surface_density_treshold"))
        self.gridLayout.addWidget(self.spinBox_analysis_surface_density_treshold, 1, 4, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 0, 9, 1, 1)
        self.doubleSpinBox_analysis_surface_density_density = QtGui.QDoubleSpinBox(self.groupBox_analysis_surface_density)
        self.doubleSpinBox_analysis_surface_density_density.setDecimals(0)
        self.doubleSpinBox_analysis_surface_density_density.setMinimum(1.0)
        self.doubleSpinBox_analysis_surface_density_density.setMaximum(100000.0)
        self.doubleSpinBox_analysis_surface_density_density.setSingleStep(100.0)
        self.doubleSpinBox_analysis_surface_density_density.setProperty("value", 800.0)
        self.doubleSpinBox_analysis_surface_density_density.setObjectName(_fromUtf8("doubleSpinBox_analysis_surface_density_density"))
        self.gridLayout.addWidget(self.doubleSpinBox_analysis_surface_density_density, 0, 4, 1, 1)
        self.checkBox_analysis_surface_density_save_all = QtGui.QCheckBox(self.groupBox_analysis_surface_density)
        self.checkBox_analysis_surface_density_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_surface_density_save_all.setObjectName(_fromUtf8("checkBox_analysis_surface_density_save_all"))
        self.gridLayout.addWidget(self.checkBox_analysis_surface_density_save_all, 0, 10, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_analysis_surface_density)
        self.groupBox_analysis_surface_density_distribution = QtGui.QGroupBox(self.groupBox_13)
        self.groupBox_analysis_surface_density_distribution.setFlat(False)
        self.groupBox_analysis_surface_density_distribution.setCheckable(True)
        self.groupBox_analysis_surface_density_distribution.setChecked(False)
        self.groupBox_analysis_surface_density_distribution.setObjectName(_fromUtf8("groupBox_analysis_surface_density_distribution"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_analysis_surface_density_distribution)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.comboBox_analysis_surface_density_distribution_channel_convex = QtGui.QComboBox(self.groupBox_analysis_surface_density_distribution)
        self.comboBox_analysis_surface_density_distribution_channel_convex.setObjectName(_fromUtf8("comboBox_analysis_surface_density_distribution_channel_convex"))
        self.gridLayout_8.addWidget(self.comboBox_analysis_surface_density_distribution_channel_convex, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_8.addWidget(self.label_18, 0, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.groupBox_analysis_surface_density_distribution)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_8.addWidget(self.line_7, 0, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 1, 0, 1, 1)
        self.comboBox_analysis_surface_density_distribution_channel_density = QtGui.QComboBox(self.groupBox_analysis_surface_density_distribution)
        self.comboBox_analysis_surface_density_distribution_channel_density.setObjectName(_fromUtf8("comboBox_analysis_surface_density_distribution_channel_density"))
        self.gridLayout_8.addWidget(self.comboBox_analysis_surface_density_distribution_channel_density, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 0, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 1, 3, 1, 1)
        self.spinBox_analysis_surface_density_distribution_treshold = QtGui.QSpinBox(self.groupBox_analysis_surface_density_distribution)
        self.spinBox_analysis_surface_density_distribution_treshold.setMinimum(1)
        self.spinBox_analysis_surface_density_distribution_treshold.setMaximum(1000)
        self.spinBox_analysis_surface_density_distribution_treshold.setProperty("value", 80)
        self.spinBox_analysis_surface_density_distribution_treshold.setObjectName(_fromUtf8("spinBox_analysis_surface_density_distribution_treshold"))
        self.gridLayout_8.addWidget(self.spinBox_analysis_surface_density_distribution_treshold, 1, 4, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 0, 9, 1, 1)
        self.doubleSpinBox_analysis_surface_density_distribution_density = QtGui.QDoubleSpinBox(self.groupBox_analysis_surface_density_distribution)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setDecimals(0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setMaximum(100000.0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setSingleStep(100.0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setProperty("value", 800.0)
        self.doubleSpinBox_analysis_surface_density_distribution_density.setObjectName(_fromUtf8("doubleSpinBox_analysis_surface_density_distribution_density"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_analysis_surface_density_distribution_density, 0, 4, 1, 1)
        self.comboBox_analysis_surface_density_distribution_channel_reference = QtGui.QComboBox(self.groupBox_analysis_surface_density_distribution)
        self.comboBox_analysis_surface_density_distribution_channel_reference.setObjectName(_fromUtf8("comboBox_analysis_surface_density_distribution_channel_reference"))
        self.gridLayout_8.addWidget(self.comboBox_analysis_surface_density_distribution_channel_reference, 2, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_analysis_surface_density_distribution)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 2, 0, 1, 1)
        self.checkBox_analysis_surface_density_distribution_save_all = QtGui.QCheckBox(self.groupBox_analysis_surface_density_distribution)
        self.checkBox_analysis_surface_density_distribution_save_all.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_analysis_surface_density_distribution_save_all.setObjectName(_fromUtf8("checkBox_analysis_surface_density_distribution_save_all"))
        self.gridLayout_8.addWidget(self.checkBox_analysis_surface_density_distribution_save_all, 0, 10, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_analysis_surface_density_distribution)
        self.verticalLayout_5.addWidget(self.groupBox_13)
        self.groupBox_15 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_15.setFlat(True)
        self.groupBox_15.setCheckable(False)
        self.groupBox_15.setChecked(False)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_analysis_export_coords = QtGui.QGroupBox(self.groupBox_15)
        self.groupBox_analysis_export_coords.setFlat(False)
        self.groupBox_analysis_export_coords.setCheckable(True)
        self.groupBox_analysis_export_coords.setChecked(False)
        self.groupBox_analysis_export_coords.setObjectName(_fromUtf8("groupBox_analysis_export_coords"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_analysis_export_coords)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12.addWidget(self.groupBox_analysis_export_coords)
        self.groupBox_analysis_export_pdb = QtGui.QGroupBox(self.groupBox_15)
        self.groupBox_analysis_export_pdb.setFlat(False)
        self.groupBox_analysis_export_pdb.setCheckable(True)
        self.groupBox_analysis_export_pdb.setChecked(False)
        self.groupBox_analysis_export_pdb.setObjectName(_fromUtf8("groupBox_analysis_export_pdb"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_analysis_export_pdb)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.verticalLayout_12.addWidget(self.groupBox_analysis_export_pdb)
        self.checkBox_analysis_export_plots = QtGui.QGroupBox(self.groupBox_15)
        self.checkBox_analysis_export_plots.setFlat(True)
        self.checkBox_analysis_export_plots.setCheckable(True)
        self.checkBox_analysis_export_plots.setChecked(False)
        self.checkBox_analysis_export_plots.setObjectName(_fromUtf8("checkBox_analysis_export_plots"))
        self.verticalLayout_12.addWidget(self.checkBox_analysis_export_plots)
        self.verticalLayout_5.addWidget(self.groupBox_15)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.pushButton_analysis_run = QtGui.QPushButton(Dialog_analysis)
        self.pushButton_analysis_run.setObjectName(_fromUtf8("pushButton_analysis_run"))
        self.horizontalLayout.addWidget(self.pushButton_analysis_run)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.actionSelect_file = QtGui.QAction(Dialog_analysis)
        self.actionSelect_file.setCheckable(False)
        self.actionSelect_file.setObjectName(_fromUtf8("actionSelect_file"))

        self.retranslateUi(Dialog_analysis)
        QtCore.QMetaObject.connectSlotsByName(Dialog_analysis)

    def retranslateUi(self, Dialog_analysis):
        Dialog_analysis.setWindowTitle(_translate("Dialog_analysis", "Analysis runner tool", None))
        self.radioButton_analysis_single.setText(_translate("Dialog_analysis", "Single", None))
        self.radioButton_analysis_batch.setText(_translate("Dialog_analysis", "Batch", None))
        self.pushButton_analysis_batch_choose_folder.setText(_translate("Dialog_analysis", "Choose folder", None))
        self.lineEdit_analysis_folder_name.setPlaceholderText(_translate("Dialog_analysis", "Folder name", None))
        self.groupBox.setTitle(_translate("Dialog_analysis", "Measurements", None))
        self.groupBox_analysis_nlp.setTitle(_translate("Dialog_analysis", "NLP per channel", None))
        self.groupBox_analysis_convex_hull.setTitle(_translate("Dialog_analysis", "Convex hull volume", None))
        self.groupBox_analysis_quality_control.setTitle(_translate("Dialog_analysis", "Quality control", None))
        self.groupBox_2.setTitle(_translate("Dialog_analysis", "Cluster analysis", None))
        self.groupBox_analysis_dbscan.setTitle(_translate("Dialog_analysis", "DBSCAN", None))
        self.label_7.setText(_translate("Dialog_analysis", "Eps (nm)", None))
        self.label_8.setText(_translate("Dialog_analysis", "MinN", None))
        self.checkBox_analysis_dbscan_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.checkBox_analysis_dbscan_export_pdb.setText(_translate("Dialog_analysis", "Export in .pdb", None))
        self.groupBox_analysis_bayesian.setTitle(_translate("Dialog_analysis", "Bayesian", None))
        self.label_analysis_bayesian_rseqminlabel.setText(_translate("Dialog_analysis", "Rsequence min", None))
        self.label_analysis_bayesian_rseqmaxlabel.setText(_translate("Dialog_analysis", "Rsequence max", None))
        self.label_analysis_bayesian_rseqdifflabel.setText(_translate("Dialog_analysis", "Rsequence diff", None))
        self.label_analysis_bayesian_alphalabel.setText(_translate("Dialog_analysis", "Alpha", None))
        self.checkBox_analysis_bayesian_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.label_analysis_bayesian_thseqminlabel.setText(_translate("Dialog_analysis", "Thsequence min", None))
        self.label_analysis_bayesian_thseqmaxlabel.setText(_translate("Dialog_analysis", "Thsequence max", None))
        self.label_analysis_bayesian_thseqdifflabel.setText(_translate("Dialog_analysis", "Thsequence diff", None))
        self.label_analysis_bayesian_pbackgroundlabel.setText(_translate("Dialog_analysis", "Pbackground", None))
        self.checkBox_analysis_bayesian_usehistogram.setText(_translate("Dialog_analysis", "Use histogram", None))
        self.pushButton_analysis_bayesian_choose_file.setText(_translate("Dialog_analysis", "Choose file", None))
        self.lineEdit_analysis_bayesian_histogramlinedit.setPlaceholderText(_translate("Dialog_analysis", "Histogram file name", None))
        self.groupBox_4.setTitle(_translate("Dialog_analysis", "Internalization", None))
        self.groupBox_analysis_internalization_surface.setTitle(_translate("Dialog_analysis", "Distance from surface", None))
        self.label_3.setText(_translate("Dialog_analysis", "Threshold (nm)", None))
        self.label_4.setText(_translate("Dialog_analysis", "Internalization distance calculation channel", None))
        self.label_15.setText(_translate("Dialog_analysis", "Convex hull maker channel", None))
        self.checkBox_analysis_internalization_surface_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.groupBox_analysis_internalization_dr.setTitle(_translate("Dialog_analysis", "Distance from center of mass", None))
        self.label_16.setText(_translate("Dialog_analysis", "Internalization Distance calculation channel", None))
        self.checkBox_analysis_internalization_dr_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.groupBox_6.setTitle(_translate("Dialog_analysis", "Minimum distances", None))
        self.groupBox_analysis_euclidean_within.setTitle(_translate("Dialog_analysis", "Euclidean, within channel", None))
        self.checkBox_analysis_euclidean_within_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.groupBox_analysis_euclidean_between.setTitle(_translate("Dialog_analysis", "Euclidean, between channels", None))
        self.label_5.setText(_translate("Dialog_analysis", "Minimum distance of points of channel", None))
        self.label_14.setText(_translate("Dialog_analysis", "From channel", None))
        self.groupBox_analysis_euclidean_between_confocal.setTitle(_translate("Dialog_analysis", "Reference channel from confocal", None))
        self.label_2.setText(_translate("Dialog_analysis", "Peak det.(%)", None))
        self.label_23.setText(_translate("Dialog_analysis", "dist.(nm)", None))
        self.label_24.setText(_translate("Dialog_analysis", "pix. int. (%)", None))
        self.checkBox_analysis_euclidean_between_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.groupBox_analysis_euclidean_surface_between.setTitle(_translate("Dialog_analysis", "Surface, between channels", None))
        self.label_13.setText(_translate("Dialog_analysis", "Distance calculation channel", None))
        self.label_12.setText(_translate("Dialog_analysis", "Reference hull maker channel", None))
        self.label_6.setText(_translate("Dialog_analysis", "Convex hull maker channel", None))
        self.label.setText(_translate("Dialog_analysis", "Distance limit from convex hull (nm)", None))
        self.checkBox_analysis_euclidean_surface_between_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.checkBox_analysis_euclidean_surface_between_export_pdb.setText(_translate("Dialog_analysis", "Export in .pdb", None))
        self.groupBox_13.setTitle(_translate("Dialog_analysis", "Surface Density", None))
        self.groupBox_analysis_surface_density.setTitle(_translate("Dialog_analysis", "Measure surface density", None))
        self.label_11.setText(_translate("Dialog_analysis", "Convex hull maker channel", None))
        self.label_17.setText(_translate("Dialog_analysis", "Density calculation channel", None))
        self.label_9.setText(_translate("Dialog_analysis", "Sampling density (NLP/µm^2)", None))
        self.label_10.setText(_translate("Dialog_analysis", "Density probe radius (nm)", None))
        self.checkBox_analysis_surface_density_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.groupBox_analysis_surface_density_distribution.setTitle(_translate("Dialog_analysis", "Measure surface density distribution relative to reference", None))
        self.label_18.setText(_translate("Dialog_analysis", "Convex hull maker channel", None))
        self.label_19.setText(_translate("Dialog_analysis", "Density calculation channel", None))
        self.label_20.setText(_translate("Dialog_analysis", "Sampling density (NLP/µm^2)", None))
        self.label_21.setText(_translate("Dialog_analysis", "Density probe radius [nm]", None))
        self.label_22.setText(_translate("Dialog_analysis", "Reference channel", None))
        self.checkBox_analysis_surface_density_distribution_save_all.setText(_translate("Dialog_analysis", "Save all data", None))
        self.groupBox_15.setTitle(_translate("Dialog_analysis", "Export data", None))
        self.groupBox_analysis_export_coords.setTitle(_translate("Dialog_analysis", "Export coordinates", None))
        self.groupBox_analysis_export_pdb.setTitle(_translate("Dialog_analysis", "Export to .pdb", None))
        self.checkBox_analysis_export_plots.setTitle(_translate("Dialog_analysis", "Display plots", None))
        self.pushButton_analysis_run.setText(_translate("Dialog_analysis", "Run", None))
        self.actionSelect_file.setText(_translate("Dialog_analysis", "select_file", None))

