# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\dialog_tool_lut.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog_lut(object):
    def setupUi(self, Dialog_lut):
        Dialog_lut.setObjectName(_fromUtf8("Dialog_lut"))
        Dialog_lut.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_lut.resize(874, 376)
        Dialog_lut.setStyleSheet(_fromUtf8("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}"))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog_lut)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(Dialog_lut)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_4 = QtGui.QWidget(self.groupBox_3)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widget_3 = QtGui.QWidget(self.widget_4)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboBox_storm_channel_changer = QtGui.QComboBox(self.widget_3)
        self.comboBox_storm_channel_changer.setObjectName(_fromUtf8("comboBox_storm_channel_changer"))
        self.horizontalLayout_3.addWidget(self.comboBox_storm_channel_changer)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.widget_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.spinBox_storm_LUT_lower = QtGui.QSpinBox(self.widget_4)
        self.spinBox_storm_LUT_lower.setMaximum(100)
        self.spinBox_storm_LUT_lower.setObjectName(_fromUtf8("spinBox_storm_LUT_lower"))
        self.horizontalLayout_5.addWidget(self.spinBox_storm_LUT_lower)
        self.label_2 = QtGui.QLabel(self.widget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spinBox_storm_LUT_upper = QtGui.QSpinBox(self.widget_4)
        self.spinBox_storm_LUT_upper.setMaximum(100)
        self.spinBox_storm_LUT_upper.setProperty("value", 100)
        self.spinBox_storm_LUT_upper.setObjectName(_fromUtf8("spinBox_storm_LUT_upper"))
        self.horizontalLayout_5.addWidget(self.spinBox_storm_LUT_upper)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.widget_3.raise_()
        self.verticalLayout_3.addWidget(self.widget_4)
        self.verticalLayout_storm_lut = QtGui.QVBoxLayout()
        self.verticalLayout_storm_lut.setObjectName(_fromUtf8("verticalLayout_storm_lut"))
        self.verticalLayout_3.addLayout(self.verticalLayout_storm_lut)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_5 = QtGui.QWidget(self.groupBox_2)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget_2 = QtGui.QWidget(self.widget_5)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_confocal_channel_changer = QtGui.QComboBox(self.widget_2)
        self.comboBox_confocal_channel_changer.setObjectName(_fromUtf8("comboBox_confocal_channel_changer"))
        self.horizontalLayout_2.addWidget(self.comboBox_confocal_channel_changer)
        self.verticalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.widget_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.spinBox_confocal_LUT_lower = QtGui.QSpinBox(self.widget_5)
        self.spinBox_confocal_LUT_lower.setMaximum(100)
        self.spinBox_confocal_LUT_lower.setObjectName(_fromUtf8("spinBox_confocal_LUT_lower"))
        self.horizontalLayout_6.addWidget(self.spinBox_confocal_LUT_lower)
        self.label_4 = QtGui.QLabel(self.widget_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinBox_confocal_LUT_upper = QtGui.QSpinBox(self.widget_5)
        self.spinBox_confocal_LUT_upper.setMaximum(100)
        self.spinBox_confocal_LUT_upper.setProperty("value", 100)
        self.spinBox_confocal_LUT_upper.setObjectName(_fromUtf8("spinBox_confocal_LUT_upper"))
        self.horizontalLayout_6.addWidget(self.spinBox_confocal_LUT_upper)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_confocal_lut = QtGui.QVBoxLayout()
        self.verticalLayout_confocal_lut.setObjectName(_fromUtf8("verticalLayout_confocal_lut"))
        self.verticalLayout_2.addLayout(self.verticalLayout_confocal_lut)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget)
        self.layoutWidget = QtGui.QWidget(Dialog_lut)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.layoutWidget1 = QtGui.QWidget(Dialog_lut)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.layoutWidget2 = QtGui.QWidget(Dialog_lut)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))

        self.retranslateUi(Dialog_lut)
        QtCore.QMetaObject.connectSlotsByName(Dialog_lut)

    def retranslateUi(self, Dialog_lut):
        Dialog_lut.setWindowTitle(_translate("Dialog_lut", "LUT settings tool", None))
        self.groupBox_3.setTitle(_translate("Dialog_lut", "STORM LUT", None))
        self.label.setText(_translate("Dialog_lut", "Lower threshold", None))
        self.label_2.setText(_translate("Dialog_lut", "Upper threshold", None))
        self.groupBox_2.setTitle(_translate("Dialog_lut", "Confocal LUT", None))
        self.label_3.setText(_translate("Dialog_lut", "Lower threshold", None))
        self.label_4.setText(_translate("Dialog_lut", "Upper threshold", None))

