# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(951, 735)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/molecules2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QWidget{\n"
"    background-color: rgb(67, 67, 67);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QToolTip { \n"
"    color: #000;\n"
"}\n"
"QTabBar::tab {\n"
"    border: 1px #fff;\n"
"    border-top-style :solid;\n"
"    border-right-style :solid; \n"
"    border-bottom-style :none; \n"
"    border-left-style :solid;\n"
"    padding: 4px 6px;\n"
"    margin: 0px 4px;\n"
"/*\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    min-width: 90px;\n"
"    min-height: 75px;\n"
"*/    \n"
"}\n"
"QTabBar::tab:selected{\n"
"    background-color: rgb(87,87,87);\n"
"    border: 1px blue;\n"
"    border-top-style :solid;\n"
"    border-right-style :solid; \n"
"    border-bottom-style :none; \n"
"    border-left-style :solid;\n"
"    padding: 4px 6px;\n"
"}\n"
""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 235))
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.frame_images_actions = QtGui.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_images_actions.setFont(font)
        self.frame_images_actions.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_images_actions.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_images_actions.setLineWidth(1)
        self.frame_images_actions.setObjectName(_fromUtf8("frame_images_actions"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_images_actions)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_storm_top_controls = QtGui.QGroupBox(self.frame_images_actions)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_top_controls.setFont(font)
        self.groupBox_storm_top_controls.setFlat(False)
        self.groupBox_storm_top_controls.setCheckable(False)
        self.groupBox_storm_top_controls.setObjectName(_fromUtf8("groupBox_storm_top_controls"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_storm_top_controls)
        self.verticalLayout_5.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget_storm_tabs = QtGui.QTabWidget(self.groupBox_storm_top_controls)
        self.tabWidget_storm_tabs.setStyleSheet(_fromUtf8(""))
        self.tabWidget_storm_tabs.setUsesScrollButtons(True)
        self.tabWidget_storm_tabs.setDocumentMode(True)
        self.tabWidget_storm_tabs.setObjectName(_fromUtf8("tabWidget_storm_tabs"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.pushButton_open_storm = QtGui.QPushButton(self.tab)
        self.pushButton_open_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_open_storm.setObjectName(_fromUtf8("pushButton_open_storm"))
        self.horizontalLayout_10.addWidget(self.pushButton_open_storm)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.pushButton_close_all_storm = QtGui.QPushButton(self.tab)
        self.pushButton_close_all_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_all_storm.setObjectName(_fromUtf8("pushButton_close_all_storm"))
        self.horizontalLayout_10.addWidget(self.pushButton_close_all_storm)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.storm_images_list = QtGui.QListWidget(self.tab)
        self.storm_images_list.setObjectName(_fromUtf8("storm_images_list"))
        self.verticalLayout.addWidget(self.storm_images_list)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButton_show_storm = QtGui.QPushButton(self.tab)
        self.pushButton_show_storm.setObjectName(_fromUtf8("pushButton_show_storm"))
        self.horizontalLayout_6.addWidget(self.pushButton_show_storm)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_unload_storm = QtGui.QPushButton(self.tab)
        self.pushButton_unload_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_unload_storm.setObjectName(_fromUtf8("pushButton_unload_storm"))
        self.horizontalLayout_6.addWidget(self.pushButton_unload_storm)
        self.pushButton_close_storm = QtGui.QPushButton(self.tab)
        self.pushButton_close_storm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_storm.setObjectName(_fromUtf8("pushButton_close_storm"))
        self.horizontalLayout_6.addWidget(self.pushButton_close_storm)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/selection13.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_storm_tabs.addTab(self.tab, icon1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 280, 88))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_19.setMargin(0)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.widget_5 = QtGui.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_storm_config_fileheader = QtGui.QGroupBox(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_config_fileheader.setFont(font)
        self.groupBox_storm_config_fileheader.setFlat(True)
        self.groupBox_storm_config_fileheader.setObjectName(_fromUtf8("groupBox_storm_config_fileheader"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_storm_config_fileheader)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_26 = QtGui.QLabel(self.groupBox_storm_config_fileheader)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_9.addWidget(self.label_26, 2, 0, 1, 1)
        self.spinBox_storm_config_fileheader_z = QtGui.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_z.setProperty("value", 18)
        self.spinBox_storm_config_fileheader_z.setObjectName(_fromUtf8("spinBox_storm_config_fileheader_z"))
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_z, 5, 1, 1, 1)
        self.spinBox_storm_config_fileheader_frame = QtGui.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_frame.setProperty("value", 13)
        self.spinBox_storm_config_fileheader_frame.setObjectName(_fromUtf8("spinBox_storm_config_fileheader_frame"))
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_frame, 3, 6, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_storm_config_fileheader)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_9.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_storm_config_fileheader)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_9.addWidget(self.label_32, 3, 5, 1, 1)
        self.spinBox_storm_config_fileheader_localization_precision = QtGui.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_localization_precision.setProperty("value", 20)
        self.spinBox_storm_config_fileheader_localization_precision.setObjectName(_fromUtf8("spinBox_storm_config_fileheader_localization_precision"))
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_localization_precision, 3, 3, 1, 1)
        self.spinBox_storm_config_fileheader_y = QtGui.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_y.setMinimum(1)
        self.spinBox_storm_config_fileheader_y.setProperty("value", 24)
        self.spinBox_storm_config_fileheader_y.setObjectName(_fromUtf8("spinBox_storm_config_fileheader_y"))
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_y, 3, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_storm_config_fileheader)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_9.addWidget(self.label_29, 2, 2, 1, 1)
        self.spinBox_storm_config_fileheader_photon = QtGui.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_photon.setProperty("value", 19)
        self.spinBox_storm_config_fileheader_photon.setObjectName(_fromUtf8("spinBox_storm_config_fileheader_photon"))
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_photon, 2, 6, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_storm_config_fileheader)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_9.addWidget(self.label_31, 2, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem2, 2, 7, 1, 1)
        self.spinBox_storm_config_fileheader_channel_name = QtGui.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_channel_name.setProperty("value", 1)
        self.spinBox_storm_config_fileheader_channel_name.setObjectName(_fromUtf8("spinBox_storm_config_fileheader_channel_name"))
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_channel_name, 2, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_storm_config_fileheader)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_9.addWidget(self.label_27, 5, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_storm_config_fileheader)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_9.addWidget(self.label_30, 3, 2, 1, 1)
        self.spinBox_storm_config_fileheader_x = QtGui.QSpinBox(self.groupBox_storm_config_fileheader)
        self.spinBox_storm_config_fileheader_x.setMinimum(1)
        self.spinBox_storm_config_fileheader_x.setProperty("value", 23)
        self.spinBox_storm_config_fileheader_x.setObjectName(_fromUtf8("spinBox_storm_config_fileheader_x"))
        self.gridLayout_9.addWidget(self.spinBox_storm_config_fileheader_x, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_storm_config_fileheader)
        self.verticalLayout_19.addWidget(self.widget_5)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_storm_config_display = QtGui.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_config_display.setFont(font)
        self.groupBox_storm_config_display.setFlat(True)
        self.groupBox_storm_config_display.setCheckable(True)
        self.groupBox_storm_config_display.setObjectName(_fromUtf8("groupBox_storm_config_display"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_storm_config_display)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_14 = QtGui.QLabel(self.groupBox_storm_config_display)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.spinBox_storm_config_dot_size = QtGui.QSpinBox(self.groupBox_storm_config_display)
        self.spinBox_storm_config_dot_size.setMinimum(1)
        self.spinBox_storm_config_dot_size.setMaximum(100)
        self.spinBox_storm_config_dot_size.setProperty("value", 30)
        self.spinBox_storm_config_dot_size.setObjectName(_fromUtf8("spinBox_storm_config_dot_size"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_storm_config_dot_size)
        self.horizontalLayout_13.addWidget(self.groupBox_storm_config_display)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.pushButton_apply_storm_config = QtGui.QPushButton(self.tab_2)
        self.pushButton_apply_storm_config.setObjectName(_fromUtf8("pushButton_apply_storm_config"))
        self.horizontalLayout_13.addWidget(self.pushButton_apply_storm_config)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/settings48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_storm_tabs.addTab(self.tab_2, icon2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.scrollArea = QtGui.QScrollArea(self.tab_6)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 213, 268))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.widget_3 = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_9.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_storm_filter_z = QtGui.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_z.setFont(font)
        self.groupBox_storm_filter_z.setFlat(True)
        self.groupBox_storm_filter_z.setCheckable(True)
        self.groupBox_storm_filter_z.setChecked(False)
        self.groupBox_storm_filter_z.setObjectName(_fromUtf8("groupBox_storm_filter_z"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_storm_filter_z)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_storm_filter_z)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_storm_filter_z_from = QtGui.QSpinBox(self.groupBox_storm_filter_z)
        self.spinBox_storm_filter_z_from.setMinimum(-10000)
        self.spinBox_storm_filter_z_from.setMaximum(10000)
        self.spinBox_storm_filter_z_from.setSingleStep(10)
        self.spinBox_storm_filter_z_from.setProperty("value", -300)
        self.spinBox_storm_filter_z_from.setObjectName(_fromUtf8("spinBox_storm_filter_z_from"))
        self.horizontalLayout_2.addWidget(self.spinBox_storm_filter_z_from)
        self.label_2 = QtGui.QLabel(self.groupBox_storm_filter_z)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_storm_filter_z_to = QtGui.QSpinBox(self.groupBox_storm_filter_z)
        self.spinBox_storm_filter_z_to.setMinimum(-10000)
        self.spinBox_storm_filter_z_to.setMaximum(10000)
        self.spinBox_storm_filter_z_to.setSingleStep(10)
        self.spinBox_storm_filter_z_to.setProperty("value", 300)
        self.spinBox_storm_filter_z_to.setObjectName(_fromUtf8("spinBox_storm_filter_z_to"))
        self.horizontalLayout_2.addWidget(self.spinBox_storm_filter_z_to)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_z)
        self.groupBox_storm_filter_photon = QtGui.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_photon.setFont(font)
        self.groupBox_storm_filter_photon.setFlat(True)
        self.groupBox_storm_filter_photon.setCheckable(True)
        self.groupBox_storm_filter_photon.setChecked(False)
        self.groupBox_storm_filter_photon.setObjectName(_fromUtf8("groupBox_storm_filter_photon"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_storm_filter_photon)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_3 = QtGui.QLabel(self.groupBox_storm_filter_photon)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_15.addWidget(self.label_3)
        self.spinBox_storm_filter_photon_from = QtGui.QSpinBox(self.groupBox_storm_filter_photon)
        self.spinBox_storm_filter_photon_from.setMinimum(0)
        self.spinBox_storm_filter_photon_from.setMaximum(10000000)
        self.spinBox_storm_filter_photon_from.setSingleStep(100)
        self.spinBox_storm_filter_photon_from.setProperty("value", 0)
        self.spinBox_storm_filter_photon_from.setObjectName(_fromUtf8("spinBox_storm_filter_photon_from"))
        self.horizontalLayout_15.addWidget(self.spinBox_storm_filter_photon_from)
        self.label_7 = QtGui.QLabel(self.groupBox_storm_filter_photon)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_15.addWidget(self.label_7)
        self.spinBox_storm_filter_photon_to = QtGui.QSpinBox(self.groupBox_storm_filter_photon)
        self.spinBox_storm_filter_photon_to.setMaximum(10000000)
        self.spinBox_storm_filter_photon_to.setSingleStep(100)
        self.spinBox_storm_filter_photon_to.setProperty("value", 5000000)
        self.spinBox_storm_filter_photon_to.setObjectName(_fromUtf8("spinBox_storm_filter_photon_to"))
        self.horizontalLayout_15.addWidget(self.spinBox_storm_filter_photon_to)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_photon)
        self.groupBox_storm_filter_frame = QtGui.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_frame.setFont(font)
        self.groupBox_storm_filter_frame.setFlat(True)
        self.groupBox_storm_filter_frame.setCheckable(True)
        self.groupBox_storm_filter_frame.setChecked(False)
        self.groupBox_storm_filter_frame.setObjectName(_fromUtf8("groupBox_storm_filter_frame"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_storm_filter_frame)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_9 = QtGui.QLabel(self.groupBox_storm_filter_frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_16.addWidget(self.label_9)
        self.spinBox_storm_filter_frame_from = QtGui.QSpinBox(self.groupBox_storm_filter_frame)
        self.spinBox_storm_filter_frame_from.setMinimum(0)
        self.spinBox_storm_filter_frame_from.setMaximum(1000000)
        self.spinBox_storm_filter_frame_from.setSingleStep(10)
        self.spinBox_storm_filter_frame_from.setProperty("value", 0)
        self.spinBox_storm_filter_frame_from.setObjectName(_fromUtf8("spinBox_storm_filter_frame_from"))
        self.horizontalLayout_16.addWidget(self.spinBox_storm_filter_frame_from)
        self.label_11 = QtGui.QLabel(self.groupBox_storm_filter_frame)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_16.addWidget(self.label_11)
        self.spinBox_storm_filter_frame_to = QtGui.QSpinBox(self.groupBox_storm_filter_frame)
        self.spinBox_storm_filter_frame_to.setMaximum(1000000)
        self.spinBox_storm_filter_frame_to.setSingleStep(10)
        self.spinBox_storm_filter_frame_to.setProperty("value", 5000)
        self.spinBox_storm_filter_frame_to.setObjectName(_fromUtf8("spinBox_storm_filter_frame_to"))
        self.horizontalLayout_16.addWidget(self.spinBox_storm_filter_frame_to)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_frame)
        self.groupBox_storm_filter_ROI = QtGui.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_ROI.setFont(font)
        self.groupBox_storm_filter_ROI.setFlat(True)
        self.groupBox_storm_filter_ROI.setCheckable(True)
        self.groupBox_storm_filter_ROI.setChecked(False)
        self.groupBox_storm_filter_ROI.setObjectName(_fromUtf8("groupBox_storm_filter_ROI"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_storm_filter_ROI)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.comboBox_storm_filter_ROI_channel = QtGui.QComboBox(self.groupBox_storm_filter_ROI)
        self.comboBox_storm_filter_ROI_channel.setObjectName(_fromUtf8("comboBox_storm_filter_ROI_channel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.comboBox_storm_filter_ROI_channel)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_ROI)
        self.groupBox_storm_filter_localdensity = QtGui.QGroupBox(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_filter_localdensity.setFont(font)
        self.groupBox_storm_filter_localdensity.setFlat(True)
        self.groupBox_storm_filter_localdensity.setCheckable(True)
        self.groupBox_storm_filter_localdensity.setChecked(False)
        self.groupBox_storm_filter_localdensity.setObjectName(_fromUtf8("groupBox_storm_filter_localdensity"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_storm_filter_localdensity)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.widget_11 = QtGui.QWidget(self.groupBox_storm_filter_localdensity)
        self.widget_11.setObjectName(_fromUtf8("widget_11"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget_11)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.doubleSpinBox_storm_filter_localdensity_maxradius = QtGui.QDoubleSpinBox(self.widget_11)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setMaximum(100000.0)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setSingleStep(10.0)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setProperty("value", 100.0)
        self.doubleSpinBox_storm_filter_localdensity_maxradius.setObjectName(_fromUtf8("doubleSpinBox_storm_filter_localdensity_maxradius"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_storm_filter_localdensity_maxradius, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget_11)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.spinBox_storm_filter_localdensity_min_num = QtGui.QSpinBox(self.widget_11)
        self.spinBox_storm_filter_localdensity_min_num.setSuffix(_fromUtf8(""))
        self.spinBox_storm_filter_localdensity_min_num.setMaximum(1000)
        self.spinBox_storm_filter_localdensity_min_num.setProperty("value", 3)
        self.spinBox_storm_filter_localdensity_min_num.setObjectName(_fromUtf8("spinBox_storm_filter_localdensity_min_num"))
        self.gridLayout_6.addWidget(self.spinBox_storm_filter_localdensity_min_num, 0, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget_11)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_11, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_storm_filter_localdensity)
        self.verticalLayout_10.addWidget(self.widget_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_8.addWidget(self.scrollArea)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.pushButton_apply_storm_filters = QtGui.QPushButton(self.tab_6)
        self.pushButton_apply_storm_filters.setObjectName(_fromUtf8("pushButton_apply_storm_filters"))
        self.horizontalLayout_4.addWidget(self.pushButton_apply_storm_filters)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/filter15.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_storm_tabs.addTab(self.tab_6, icon3, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab_7)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.storm_roi_list = QtGui.QListWidget(self.tab_7)
        self.storm_roi_list.setObjectName(_fromUtf8("storm_roi_list"))
        self.verticalLayout_17.addWidget(self.storm_roi_list)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.pushButton_unselect_roi = QtGui.QPushButton(self.tab_7)
        self.pushButton_unselect_roi.setObjectName(_fromUtf8("pushButton_unselect_roi"))
        self.horizontalLayout_22.addWidget(self.pushButton_unselect_roi)
        self.pushButton_delete_roi = QtGui.QPushButton(self.tab_7)
        self.pushButton_delete_roi.setObjectName(_fromUtf8("pushButton_delete_roi"))
        self.horizontalLayout_22.addWidget(self.pushButton_delete_roi)
        self.verticalLayout_17.addLayout(self.horizontalLayout_22)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/cursor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_storm_tabs.addTab(self.tab_7, icon4, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget_storm_tabs)
        self.horizontalLayout.addWidget(self.groupBox_storm_top_controls)
        self.widget_2 = QtGui.QWidget(self.frame_images_actions)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_16.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem12)
        self.pushButton_prev_batch = QtGui.QPushButton(self.widget_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/arrow218.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prev_batch.setIcon(icon5)
        self.pushButton_prev_batch.setObjectName(_fromUtf8("pushButton_prev_batch"))
        self.verticalLayout_16.addWidget(self.pushButton_prev_batch)
        self.pushButton_next_batch = QtGui.QPushButton(self.widget_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/arrow167.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next_batch.setIcon(icon6)
        self.pushButton_next_batch.setObjectName(_fromUtf8("pushButton_next_batch"))
        self.verticalLayout_16.addWidget(self.pushButton_next_batch)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem13)
        self.horizontalLayout.addWidget(self.widget_2)
        self.groupBox_confocal_top_controls = QtGui.QGroupBox(self.frame_images_actions)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_top_controls.setFont(font)
        self.groupBox_confocal_top_controls.setObjectName(_fromUtf8("groupBox_confocal_top_controls"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_confocal_top_controls)
        self.verticalLayout_6.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tabWidget_confocal_tabs = QtGui.QTabWidget(self.groupBox_confocal_top_controls)
        self.tabWidget_confocal_tabs.setDocumentMode(True)
        self.tabWidget_confocal_tabs.setObjectName(_fromUtf8("tabWidget_confocal_tabs"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButton_open_confocal = QtGui.QPushButton(self.tab_3)
        self.pushButton_open_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_open_confocal.setObjectName(_fromUtf8("pushButton_open_confocal"))
        self.horizontalLayout_9.addWidget(self.pushButton_open_confocal)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.pushButton_close_all_confocal = QtGui.QPushButton(self.tab_3)
        self.pushButton_close_all_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_all_confocal.setObjectName(_fromUtf8("pushButton_close_all_confocal"))
        self.horizontalLayout_9.addWidget(self.pushButton_close_all_confocal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.confocal_images_list = QtGui.QListWidget(self.tab_3)
        self.confocal_images_list.setObjectName(_fromUtf8("confocal_images_list"))
        self.verticalLayout_2.addWidget(self.confocal_images_list)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton_show_confocal = QtGui.QPushButton(self.tab_3)
        self.pushButton_show_confocal.setObjectName(_fromUtf8("pushButton_show_confocal"))
        self.horizontalLayout_7.addWidget(self.pushButton_show_confocal)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem15)
        self.pushButton_unload_confocal = QtGui.QPushButton(self.tab_3)
        self.pushButton_unload_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_unload_confocal.setObjectName(_fromUtf8("pushButton_unload_confocal"))
        self.horizontalLayout_7.addWidget(self.pushButton_unload_confocal)
        self.pushButton_close_confocal = QtGui.QPushButton(self.tab_3)
        self.pushButton_close_confocal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_confocal.setObjectName(_fromUtf8("pushButton_close_confocal"))
        self.horizontalLayout_7.addWidget(self.pushButton_close_confocal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.tabWidget_confocal_tabs.addTab(self.tab_3, icon1, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_confocal_config_resize = QtGui.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_config_resize.setFont(font)
        self.groupBox_confocal_config_resize.setFlat(True)
        self.groupBox_confocal_config_resize.setObjectName(_fromUtf8("groupBox_confocal_config_resize"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_confocal_config_resize)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.radioButton_confocal_config_resize_square = QtGui.QRadioButton(self.groupBox_confocal_config_resize)
        self.radioButton_confocal_config_resize_square.setObjectName(_fromUtf8("radioButton_confocal_config_resize_square"))
        self.gridLayout_4.addWidget(self.radioButton_confocal_config_resize_square, 2, 1, 1, 1)
        self.radioButton_confocal_config_resize_cubic = QtGui.QRadioButton(self.groupBox_confocal_config_resize)
        self.radioButton_confocal_config_resize_cubic.setObjectName(_fromUtf8("radioButton_confocal_config_resize_cubic"))
        self.gridLayout_4.addWidget(self.radioButton_confocal_config_resize_cubic, 2, 2, 1, 1)
        self.radioButton_confocal_config_resize_nearest = QtGui.QRadioButton(self.groupBox_confocal_config_resize)
        self.radioButton_confocal_config_resize_nearest.setChecked(True)
        self.radioButton_confocal_config_resize_nearest.setObjectName(_fromUtf8("radioButton_confocal_config_resize_nearest"))
        self.gridLayout_4.addWidget(self.radioButton_confocal_config_resize_nearest, 0, 1, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 3, 1, 1)
        self.radioButton_confocal_config_resize_bilinear = QtGui.QRadioButton(self.groupBox_confocal_config_resize)
        self.radioButton_confocal_config_resize_bilinear.setObjectName(_fromUtf8("radioButton_confocal_config_resize_bilinear"))
        self.gridLayout_4.addWidget(self.radioButton_confocal_config_resize_bilinear, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_confocal_config_resize)
        self.groupBox_confocal_config_calibration = QtGui.QGroupBox(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_config_calibration.setFont(font)
        self.groupBox_confocal_config_calibration.setFlat(True)
        self.groupBox_confocal_config_calibration.setObjectName(_fromUtf8("groupBox_confocal_config_calibration"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_confocal_config_calibration)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_4 = QtGui.QLabel(self.groupBox_confocal_config_calibration)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_12.addWidget(self.label_4)
        self.doubleSpinBox_confocal_config_calibration_px = QtGui.QDoubleSpinBox(self.groupBox_confocal_config_calibration)
        self.doubleSpinBox_confocal_config_calibration_px.setDecimals(6)
        self.doubleSpinBox_confocal_config_calibration_px.setMaximum(2.0)
        self.doubleSpinBox_confocal_config_calibration_px.setSingleStep(0.001)
        self.doubleSpinBox_confocal_config_calibration_px.setProperty("value", 0.078)
        self.doubleSpinBox_confocal_config_calibration_px.setObjectName(_fromUtf8("doubleSpinBox_confocal_config_calibration_px"))
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_confocal_config_calibration_px)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.verticalLayout_4.addWidget(self.groupBox_confocal_config_calibration)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem18)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.pushButton_apply_confocal_config = QtGui.QPushButton(self.tab_4)
        self.pushButton_apply_confocal_config.setObjectName(_fromUtf8("pushButton_apply_confocal_config"))
        self.horizontalLayout_11.addWidget(self.pushButton_apply_confocal_config)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.tabWidget_confocal_tabs.addTab(self.tab_4, icon2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.groupBox_confocal_display_appear = QtGui.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_display_appear.setFont(font)
        self.groupBox_confocal_display_appear.setFlat(True)
        self.groupBox_confocal_display_appear.setObjectName(_fromUtf8("groupBox_confocal_display_appear"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_confocal_display_appear)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.groupBox_confocal_display_appear)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.doubleSpinBox_confocal_display_appear_transparency = QtGui.QDoubleSpinBox(self.groupBox_confocal_display_appear)
        self.doubleSpinBox_confocal_display_appear_transparency.setMaximum(1.0)
        self.doubleSpinBox_confocal_display_appear_transparency.setSingleStep(0.1)
        self.doubleSpinBox_confocal_display_appear_transparency.setProperty("value", 0.7)
        self.doubleSpinBox_confocal_display_appear_transparency.setObjectName(_fromUtf8("doubleSpinBox_confocal_display_appear_transparency"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_confocal_display_appear_transparency)
        self.label_5 = QtGui.QLabel(self.groupBox_confocal_display_appear)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_confocal_display_appear_zposition = QtGui.QSpinBox(self.groupBox_confocal_display_appear)
        self.spinBox_confocal_display_appear_zposition.setMinimum(0)
        self.spinBox_confocal_display_appear_zposition.setMaximum(100)
        self.spinBox_confocal_display_appear_zposition.setProperty("value", 7)
        self.spinBox_confocal_display_appear_zposition.setObjectName(_fromUtf8("spinBox_confocal_display_appear_zposition"))
        self.horizontalLayout_3.addWidget(self.spinBox_confocal_display_appear_zposition)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem20)
        self.verticalLayout_12.addWidget(self.groupBox_confocal_display_appear)
        self.groupBox_confocal_display_offset = QtGui.QGroupBox(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_display_offset.setFont(font)
        self.groupBox_confocal_display_offset.setFlat(True)
        self.groupBox_confocal_display_offset.setObjectName(_fromUtf8("groupBox_confocal_display_offset"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_confocal_display_offset)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_12 = QtGui.QLabel(self.groupBox_confocal_display_offset)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_17.addWidget(self.label_12)
        self.doubleSpinBox_confocal_display_offset_x = QtGui.QDoubleSpinBox(self.groupBox_confocal_display_offset)
        self.doubleSpinBox_confocal_display_offset_x.setDecimals(0)
        self.doubleSpinBox_confocal_display_offset_x.setMinimum(-100000.0)
        self.doubleSpinBox_confocal_display_offset_x.setMaximum(100000.0)
        self.doubleSpinBox_confocal_display_offset_x.setSingleStep(10.0)
        self.doubleSpinBox_confocal_display_offset_x.setObjectName(_fromUtf8("doubleSpinBox_confocal_display_offset_x"))
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_confocal_display_offset_x)
        self.label_13 = QtGui.QLabel(self.groupBox_confocal_display_offset)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_17.addWidget(self.label_13)
        self.doubleSpinBox_confocal_display_offset_y = QtGui.QDoubleSpinBox(self.groupBox_confocal_display_offset)
        self.doubleSpinBox_confocal_display_offset_y.setDecimals(0)
        self.doubleSpinBox_confocal_display_offset_y.setMinimum(-100000.0)
        self.doubleSpinBox_confocal_display_offset_y.setMaximum(100000.0)
        self.doubleSpinBox_confocal_display_offset_y.setSingleStep(10.0)
        self.doubleSpinBox_confocal_display_offset_y.setObjectName(_fromUtf8("doubleSpinBox_confocal_display_offset_y"))
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_confocal_display_offset_y)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.verticalLayout_12.addWidget(self.groupBox_confocal_display_offset)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem22)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem23)
        self.pushButton_apply_confocal_display = QtGui.QPushButton(self.tab_5)
        self.pushButton_apply_confocal_display.setObjectName(_fromUtf8("pushButton_apply_confocal_display"))
        self.horizontalLayout_5.addWidget(self.pushButton_apply_confocal_display)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/landscape.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_confocal_tabs.addTab(self.tab_5, icon7, _fromUtf8(""))
        self.verticalLayout_6.addWidget(self.tabWidget_confocal_tabs)
        self.horizontalLayout.addWidget(self.groupBox_confocal_top_controls)
        self.horizontalLayout_14.addWidget(self.frame_images_actions)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 23))
        self.menubar.setStyleSheet(_fromUtf8("QMenuBar {\n"
"    background-color: rgb(47,47,47);\n"
"    color: rgb(255,255,255);\n"
"    border: 1px solid #000;\n"
"}\n"
" \n"
"QMenuBar::item {\n"
"    background-color: rgb(47,47,47);\n"
"    color: rgb(255,255,255);\n"
"}\n"
" \n"
"QMenuBar::item::selected {\n"
"    background-color: rgb(30,30,30);\n"
"}\n"
" \n"
"QMenu {\n"
"    background-color: rgb(47,47,47);\n"
"    color: rgb(255,255,255);\n"
"    border: 1px solid #000;          \n"
"}\n"
" \n"
"QMenu::item::selected {\n"
"    background-color: rgb(30,30,30);\n"
"}"))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuSTORMView = QtGui.QMenu(self.menubar)
        self.menuSTORMView.setObjectName(_fromUtf8("menuSTORMView"))
        self.menuTools_2 = QtGui.QMenu(self.menubar)
        self.menuTools_2.setObjectName(_fromUtf8("menuTools_2"))
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.dockWidget.setFont(font)
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(0, 427))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.viewer_container = QtGui.QWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_container.sizePolicy().hasHeightForWidth())
        self.viewer_container.setSizePolicy(sizePolicy)
        self.viewer_container.setObjectName(_fromUtf8("viewer_container"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.viewer_container)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.viewer_container_layout = QtGui.QVBoxLayout()
        self.viewer_container_layout.setSpacing(6)
        self.viewer_container_layout.setObjectName(_fromUtf8("viewer_container_layout"))
        self.verticalLayout_13.addLayout(self.viewer_container_layout)
        self.verticalLayout_11.addWidget(self.viewer_container)
        self.widget_6 = QtGui.QWidget(self.dockWidgetContents)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_storm_bottom_controls = QtGui.QGroupBox(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_storm_bottom_controls.setFont(font)
        self.groupBox_storm_bottom_controls.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.groupBox_storm_bottom_controls.setFlat(True)
        self.groupBox_storm_bottom_controls.setObjectName(_fromUtf8("groupBox_storm_bottom_controls"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_storm_bottom_controls)
        self.verticalLayout_14.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.widget = QtGui.QWidget(self.groupBox_storm_bottom_controls)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.widget.setFont(font)
        self.widget.setStyleSheet(_fromUtf8("margin: 0;"))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_storm_channel1 = QtGui.QCheckBox(self.widget)
        self.checkBox_storm_channel1.setEnabled(False)
        self.checkBox_storm_channel1.setChecked(False)
        self.checkBox_storm_channel1.setObjectName(_fromUtf8("checkBox_storm_channel1"))
        self.gridLayout_2.addWidget(self.checkBox_storm_channel1, 0, 1, 1, 1)
        self.checkBox_storm_channel3 = QtGui.QCheckBox(self.widget)
        self.checkBox_storm_channel3.setEnabled(False)
        self.checkBox_storm_channel3.setChecked(False)
        self.checkBox_storm_channel3.setObjectName(_fromUtf8("checkBox_storm_channel3"))
        self.gridLayout_2.addWidget(self.checkBox_storm_channel3, 0, 3, 1, 1)
        self.checkBox_storm_channel0 = QtGui.QCheckBox(self.widget)
        self.checkBox_storm_channel0.setEnabled(False)
        self.checkBox_storm_channel0.setChecked(False)
        self.checkBox_storm_channel0.setObjectName(_fromUtf8("checkBox_storm_channel0"))
        self.gridLayout_2.addWidget(self.checkBox_storm_channel0, 0, 0, 1, 1)
        self.checkBox_storm_channel2 = QtGui.QCheckBox(self.widget)
        self.checkBox_storm_channel2.setEnabled(False)
        self.checkBox_storm_channel2.setChecked(False)
        self.checkBox_storm_channel2.setObjectName(_fromUtf8("checkBox_storm_channel2"))
        self.gridLayout_2.addWidget(self.checkBox_storm_channel2, 0, 2, 1, 1)
        self.comboBox_storm_channel1_color = QtGui.QComboBox(self.widget)
        self.comboBox_storm_channel1_color.setEnabled(False)
        self.comboBox_storm_channel1_color.setEditable(False)
        self.comboBox_storm_channel1_color.setObjectName(_fromUtf8("comboBox_storm_channel1_color"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/square-rounded-32-r.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon8, _fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/square-rounded-32-g.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon9, _fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/square-rounded-32-b.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon10, _fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/square-rounded-32-c.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon11, _fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/square-rounded-32-m.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon12, _fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/square-rounded-32-y.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_storm_channel1_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_storm_channel1_color, 1, 1, 1, 1)
        self.comboBox_storm_channel0_color = QtGui.QComboBox(self.widget)
        self.comboBox_storm_channel0_color.setEnabled(False)
        self.comboBox_storm_channel0_color.setEditable(False)
        self.comboBox_storm_channel0_color.setObjectName(_fromUtf8("comboBox_storm_channel0_color"))
        self.comboBox_storm_channel0_color.addItem(icon8, _fromUtf8(""))
        self.comboBox_storm_channel0_color.addItem(icon9, _fromUtf8(""))
        self.comboBox_storm_channel0_color.addItem(icon10, _fromUtf8(""))
        self.comboBox_storm_channel0_color.addItem(icon11, _fromUtf8(""))
        self.comboBox_storm_channel0_color.addItem(icon12, _fromUtf8(""))
        self.comboBox_storm_channel0_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_storm_channel0_color, 1, 0, 1, 1)
        self.comboBox_storm_channel2_color = QtGui.QComboBox(self.widget)
        self.comboBox_storm_channel2_color.setEnabled(False)
        self.comboBox_storm_channel2_color.setEditable(False)
        self.comboBox_storm_channel2_color.setObjectName(_fromUtf8("comboBox_storm_channel2_color"))
        self.comboBox_storm_channel2_color.addItem(icon8, _fromUtf8(""))
        self.comboBox_storm_channel2_color.addItem(icon9, _fromUtf8(""))
        self.comboBox_storm_channel2_color.addItem(icon10, _fromUtf8(""))
        self.comboBox_storm_channel2_color.addItem(icon11, _fromUtf8(""))
        self.comboBox_storm_channel2_color.addItem(icon12, _fromUtf8(""))
        self.comboBox_storm_channel2_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_storm_channel2_color, 1, 2, 1, 1)
        self.comboBox_storm_channel3_color = QtGui.QComboBox(self.widget)
        self.comboBox_storm_channel3_color.setEnabled(False)
        self.comboBox_storm_channel3_color.setEditable(False)
        self.comboBox_storm_channel3_color.setObjectName(_fromUtf8("comboBox_storm_channel3_color"))
        self.comboBox_storm_channel3_color.addItem(icon8, _fromUtf8(""))
        self.comboBox_storm_channel3_color.addItem(icon9, _fromUtf8(""))
        self.comboBox_storm_channel3_color.addItem(icon10, _fromUtf8(""))
        self.comboBox_storm_channel3_color.addItem(icon11, _fromUtf8(""))
        self.comboBox_storm_channel3_color.addItem(icon12, _fromUtf8(""))
        self.comboBox_storm_channel3_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_storm_channel3_color, 1, 3, 1, 1)
        self.label_storm_channel0_info = QtGui.QLabel(self.widget)
        self.label_storm_channel0_info.setObjectName(_fromUtf8("label_storm_channel0_info"))
        self.gridLayout_2.addWidget(self.label_storm_channel0_info, 2, 0, 1, 1)
        self.label_storm_channel1_info = QtGui.QLabel(self.widget)
        self.label_storm_channel1_info.setObjectName(_fromUtf8("label_storm_channel1_info"))
        self.gridLayout_2.addWidget(self.label_storm_channel1_info, 2, 1, 1, 1)
        self.label_storm_channel2_info = QtGui.QLabel(self.widget)
        self.label_storm_channel2_info.setObjectName(_fromUtf8("label_storm_channel2_info"))
        self.gridLayout_2.addWidget(self.label_storm_channel2_info, 2, 2, 1, 1)
        self.label_storm_channel3_info = QtGui.QLabel(self.widget)
        self.label_storm_channel3_info.setObjectName(_fromUtf8("label_storm_channel3_info"))
        self.gridLayout_2.addWidget(self.label_storm_channel3_info, 2, 3, 1, 1)
        self.verticalLayout_14.addWidget(self.widget)
        self.horizontalLayout_8.addWidget(self.groupBox_storm_bottom_controls)
        self.line_3 = QtGui.QFrame(self.widget_6)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_8.addWidget(self.line_3)
        self.groupBox_confocal_bottom_controls = QtGui.QGroupBox(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_confocal_bottom_controls.setFont(font)
        self.groupBox_confocal_bottom_controls.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.groupBox_confocal_bottom_controls.setFlat(True)
        self.groupBox_confocal_bottom_controls.setObjectName(_fromUtf8("groupBox_confocal_bottom_controls"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_confocal_bottom_controls)
        self.verticalLayout_15.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.widget_4 = QtGui.QWidget(self.groupBox_confocal_bottom_controls)
        self.widget_4.setStyleSheet(_fromUtf8("margin: 0;"))
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_confocal_channel3 = QtGui.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel3.setEnabled(False)
        self.checkBox_confocal_channel3.setChecked(False)
        self.checkBox_confocal_channel3.setObjectName(_fromUtf8("checkBox_confocal_channel3"))
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel3, 0, 3, 1, 1)
        self.checkBox_confocal_channel2 = QtGui.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel2.setEnabled(False)
        self.checkBox_confocal_channel2.setChecked(False)
        self.checkBox_confocal_channel2.setObjectName(_fromUtf8("checkBox_confocal_channel2"))
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel2, 0, 2, 1, 1)
        self.comboBox_confocal_channel2_color = QtGui.QComboBox(self.widget_4)
        self.comboBox_confocal_channel2_color.setEnabled(False)
        self.comboBox_confocal_channel2_color.setEditable(False)
        self.comboBox_confocal_channel2_color.setObjectName(_fromUtf8("comboBox_confocal_channel2_color"))
        self.comboBox_confocal_channel2_color.addItem(icon8, _fromUtf8(""))
        self.comboBox_confocal_channel2_color.addItem(icon9, _fromUtf8(""))
        self.comboBox_confocal_channel2_color.addItem(icon10, _fromUtf8(""))
        self.comboBox_confocal_channel2_color.addItem(icon11, _fromUtf8(""))
        self.comboBox_confocal_channel2_color.addItem(icon12, _fromUtf8(""))
        self.comboBox_confocal_channel2_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel2_color, 1, 2, 1, 1)
        self.checkBox_confocal_channel1 = QtGui.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel1.setEnabled(False)
        self.checkBox_confocal_channel1.setStyleSheet(_fromUtf8(""))
        self.checkBox_confocal_channel1.setChecked(False)
        self.checkBox_confocal_channel1.setObjectName(_fromUtf8("checkBox_confocal_channel1"))
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel1, 0, 1, 1, 1)
        self.checkBox_confocal_channel0 = QtGui.QCheckBox(self.widget_4)
        self.checkBox_confocal_channel0.setEnabled(False)
        self.checkBox_confocal_channel0.setChecked(False)
        self.checkBox_confocal_channel0.setObjectName(_fromUtf8("checkBox_confocal_channel0"))
        self.gridLayout_3.addWidget(self.checkBox_confocal_channel0, 0, 0, 1, 1)
        self.comboBox_confocal_channel3_color = QtGui.QComboBox(self.widget_4)
        self.comboBox_confocal_channel3_color.setEnabled(False)
        self.comboBox_confocal_channel3_color.setEditable(False)
        self.comboBox_confocal_channel3_color.setObjectName(_fromUtf8("comboBox_confocal_channel3_color"))
        self.comboBox_confocal_channel3_color.addItem(icon8, _fromUtf8(""))
        self.comboBox_confocal_channel3_color.addItem(icon9, _fromUtf8(""))
        self.comboBox_confocal_channel3_color.addItem(icon10, _fromUtf8(""))
        self.comboBox_confocal_channel3_color.addItem(icon11, _fromUtf8(""))
        self.comboBox_confocal_channel3_color.addItem(icon12, _fromUtf8(""))
        self.comboBox_confocal_channel3_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel3_color, 1, 3, 1, 1)
        self.comboBox_confocal_channel0_color = QtGui.QComboBox(self.widget_4)
        self.comboBox_confocal_channel0_color.setEnabled(False)
        self.comboBox_confocal_channel0_color.setEditable(False)
        self.comboBox_confocal_channel0_color.setObjectName(_fromUtf8("comboBox_confocal_channel0_color"))
        self.comboBox_confocal_channel0_color.addItem(icon8, _fromUtf8(""))
        self.comboBox_confocal_channel0_color.addItem(icon9, _fromUtf8(""))
        self.comboBox_confocal_channel0_color.addItem(icon10, _fromUtf8(""))
        self.comboBox_confocal_channel0_color.addItem(icon11, _fromUtf8(""))
        self.comboBox_confocal_channel0_color.addItem(icon12, _fromUtf8(""))
        self.comboBox_confocal_channel0_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel0_color, 1, 0, 1, 1)
        self.comboBox_confocal_channel1_color = QtGui.QComboBox(self.widget_4)
        self.comboBox_confocal_channel1_color.setEnabled(False)
        self.comboBox_confocal_channel1_color.setEditable(False)
        self.comboBox_confocal_channel1_color.setObjectName(_fromUtf8("comboBox_confocal_channel1_color"))
        self.comboBox_confocal_channel1_color.addItem(icon8, _fromUtf8(""))
        self.comboBox_confocal_channel1_color.addItem(icon9, _fromUtf8(""))
        self.comboBox_confocal_channel1_color.addItem(icon10, _fromUtf8(""))
        self.comboBox_confocal_channel1_color.addItem(icon11, _fromUtf8(""))
        self.comboBox_confocal_channel1_color.addItem(icon12, _fromUtf8(""))
        self.comboBox_confocal_channel1_color.addItem(icon13, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_confocal_channel1_color, 1, 1, 1, 1)
        self.label_confocal_info = QtGui.QLabel(self.widget_4)
        self.label_confocal_info.setLineWidth(1)
        self.label_confocal_info.setObjectName(_fromUtf8("label_confocal_info"))
        self.gridLayout_3.addWidget(self.label_confocal_info, 2, 0, 1, 4)
        self.verticalLayout_15.addWidget(self.widget_4)
        self.horizontalLayout_8.addWidget(self.groupBox_confocal_bottom_controls)
        self.verticalLayout_11.addWidget(self.widget_6)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtGui.QToolBar(MainWindow)
        self.toolBar_3.setObjectName(_fromUtf8("toolBar_3"))
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar_3)
        self.actionActiveContour_selector = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/selection7.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionActiveContour_selector.setIcon(icon14)
        self.actionActiveContour_selector.setObjectName(_fromUtf8("actionActiveContour_selector"))
        self.actionLUT_changer = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/candlestick.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLUT_changer.setIcon(icon15)
        self.actionLUT_changer.setObjectName(_fromUtf8("actionLUT_changer"))
        self.actionAnalysis = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/data61.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAnalysis.setIcon(icon16)
        self.actionAnalysis.setObjectName(_fromUtf8("actionAnalysis"))
        self.actionVividSTORM_help = QtGui.QAction(MainWindow)
        self.actionVividSTORM_help.setObjectName(_fromUtf8("actionVividSTORM_help"))
        self.actionAbout_VividSTORM = QtGui.QAction(MainWindow)
        self.actionAbout_VividSTORM.setObjectName(_fromUtf8("actionAbout_VividSTORM"))
        self.actionDots = QtGui.QAction(MainWindow)
        self.actionDots.setCheckable(False)
        self.actionDots.setChecked(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/chart14.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDots.setIcon(icon17)
        self.actionDots.setObjectName(_fromUtf8("actionDots"))
        self.actionGaussian = QtGui.QAction(MainWindow)
        self.actionGaussian.setCheckable(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/line47.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGaussian.setIcon(icon18)
        self.actionGaussian.setObjectName(_fromUtf8("actionGaussian"))
        self.action3D = QtGui.QAction(MainWindow)
        self.action3D.setCheckable(False)
        self.action3D.setEnabled(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/3d76.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3D.setIcon(icon19)
        self.action3D.setObjectName(_fromUtf8("action3D"))
        self.actionShow_1_m_scale = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/scale6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShow_1_m_scale.setIcon(icon20)
        self.actionShow_1_m_scale.setObjectName(_fromUtf8("actionShow_1_m_scale"))
        self.actionOpen_STORM_files = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/file98.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_STORM_files.setIcon(icon21)
        self.actionOpen_STORM_files.setObjectName(_fromUtf8("actionOpen_STORM_files"))
        self.actionOpen_Confocal_files = QtGui.QAction(MainWindow)
        self.actionOpen_Confocal_files.setIcon(icon21)
        self.actionOpen_Confocal_files.setObjectName(_fromUtf8("actionOpen_Confocal_files"))
        self.actionExport_As_Image = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/export2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_As_Image.setIcon(icon22)
        self.actionExport_As_Image.setObjectName(_fromUtf8("actionExport_As_Image"))
        self.actionClose_STORM_files = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/delete30.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose_STORM_files.setIcon(icon23)
        self.actionClose_STORM_files.setObjectName(_fromUtf8("actionClose_STORM_files"))
        self.actionClose_Confocal_files = QtGui.QAction(MainWindow)
        self.actionClose_Confocal_files.setIcon(icon23)
        self.actionClose_Confocal_files.setObjectName(_fromUtf8("actionClose_Confocal_files"))
        self.actionSet_working_directory = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/box11.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSet_working_directory.setIcon(icon24)
        self.actionSet_working_directory.setObjectName(_fromUtf8("actionSet_working_directory"))
        self.actionPositioning_tool = QtGui.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/squares21.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPositioning_tool.setIcon(icon25)
        self.actionPositioning_tool.setObjectName(_fromUtf8("actionPositioning_tool"))
        self.actionFreehand_selecting = QtGui.QAction(MainWindow)
        self.actionFreehand_selecting.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/pencil123.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFreehand_selecting.setIcon(icon26)
        self.actionFreehand_selecting.setObjectName(_fromUtf8("actionFreehand_selecting"))
        self.actionEllipse_ROI_selecting = QtGui.QAction(MainWindow)
        self.actionEllipse_ROI_selecting.setCheckable(False)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/ellipse.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEllipse_ROI_selecting.setIcon(icon27)
        self.actionEllipse_ROI_selecting.setObjectName(_fromUtf8("actionEllipse_ROI_selecting"))
        self.actionDragging_mode = QtGui.QAction(MainWindow)
        self.actionDragging_mode.setCheckable(True)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/arrow40.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDragging_mode.setIcon(icon28)
        self.actionDragging_mode.setObjectName(_fromUtf8("actionDragging_mode"))
        self.actionCircle_ROI_selecting = QtGui.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/icons/data68.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCircle_ROI_selecting.setIcon(icon29)
        self.actionCircle_ROI_selecting.setObjectName(_fromUtf8("actionCircle_ROI_selecting"))
        self.actionImage_Registration = QtGui.QAction(MainWindow)
        self.actionImage_Registration.setIcon(icon25)
        self.actionImage_Registration.setObjectName(_fromUtf8("actionImage_Registration"))
        self.actionJoin_Result_files_in_a_folder = QtGui.QAction(MainWindow)
        self.actionJoin_Result_files_in_a_folder.setObjectName(_fromUtf8("actionJoin_Result_files_in_a_folder"))
        self.actionJoin_ROI_attribute_files_in_a_folder = QtGui.QAction(MainWindow)
        self.actionJoin_ROI_attribute_files_in_a_folder.setObjectName(_fromUtf8("actionJoin_ROI_attribute_files_in_a_folder"))
        self.actionDelete_ROI_selector = QtGui.QAction(MainWindow)
        self.actionDelete_ROI_selector.setIcon(icon23)
        self.actionDelete_ROI_selector.setObjectName(_fromUtf8("actionDelete_ROI_selector"))
        self.menuFile.addAction(self.actionOpen_STORM_files)
        self.menuFile.addAction(self.actionClose_STORM_files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Confocal_files)
        self.menuFile.addAction(self.actionClose_Confocal_files)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSet_working_directory)
        self.menuHelp.addAction(self.actionVividSTORM_help)
        self.menuHelp.addAction(self.actionAbout_VividSTORM)
        self.menuSTORMView.addAction(self.actionFreehand_selecting)
        self.menuSTORMView.addAction(self.actionEllipse_ROI_selecting)
        self.menuSTORMView.addAction(self.actionCircle_ROI_selecting)
        self.menuSTORMView.addAction(self.actionActiveContour_selector)
        self.menuSTORMView.addAction(self.actionDelete_ROI_selector)
        self.menuTools_2.addAction(self.action3D)
        self.menuTools_2.addAction(self.actionDragging_mode)
        self.menuTools_2.addAction(self.actionShow_1_m_scale)
        self.menuTools_2.addAction(self.actionLUT_changer)
        self.menuTools_2.addAction(self.actionAnalysis)
        self.menuTools_2.addSeparator()
        self.menuTools_2.addAction(self.actionJoin_Result_files_in_a_folder)
        self.menuTools_2.addAction(self.actionJoin_ROI_attribute_files_in_a_folder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSTORMView.menuAction())
        self.menubar.addAction(self.menuTools_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_2.addAction(self.actionFreehand_selecting)
        self.toolBar_2.addAction(self.actionEllipse_ROI_selecting)
        self.toolBar_2.addAction(self.actionCircle_ROI_selecting)
        self.toolBar_2.addAction(self.actionActiveContour_selector)
        self.toolBar_3.addAction(self.actionDragging_mode)
        self.toolBar_3.addAction(self.actionImage_Registration)
        self.toolBar_3.addAction(self.actionShow_1_m_scale)
        self.toolBar_3.addAction(self.actionLUT_changer)
        self.toolBar_3.addAction(self.actionAnalysis)

        self.retranslateUi(MainWindow)
        self.tabWidget_storm_tabs.setCurrentIndex(0)
        self.tabWidget_confocal_tabs.setCurrentIndex(0)
        self.comboBox_storm_channel1_color.setCurrentIndex(3)
        self.comboBox_storm_channel0_color.setCurrentIndex(4)
        self.comboBox_storm_channel2_color.setCurrentIndex(5)
        self.comboBox_storm_channel3_color.setCurrentIndex(0)
        self.comboBox_confocal_channel2_color.setCurrentIndex(2)
        self.comboBox_confocal_channel3_color.setCurrentIndex(3)
        self.comboBox_confocal_channel0_color.setCurrentIndex(0)
        self.comboBox_confocal_channel1_color.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "VividSTORM 1.5", None))
        self.groupBox_storm_top_controls.setTitle(_translate("MainWindow", "STORM images", None))
        self.pushButton_open_storm.setText(_translate("MainWindow", "Open files...", None))
        self.pushButton_close_all_storm.setText(_translate("MainWindow", "Close files", None))
        self.pushButton_show_storm.setText(_translate("MainWindow", "Show selected", None))
        self.pushButton_unload_storm.setText(_translate("MainWindow", "Unload selected", None))
        self.pushButton_close_storm.setText(_translate("MainWindow", "Close selected", None))
        self.tabWidget_storm_tabs.setTabText(self.tabWidget_storm_tabs.indexOf(self.tab), _translate("MainWindow", "Select", None))
        self.groupBox_storm_config_fileheader.setTitle(_translate("MainWindow", "File header column numbers", None))
        self.label_26.setText(_translate("MainWindow", "x", None))
        self.label_28.setText(_translate("MainWindow", "y", None))
        self.label_32.setText(_translate("MainWindow", "Frame", None))
        self.label_29.setText(_translate("MainWindow", "Channel name", None))
        self.label_31.setText(_translate("MainWindow", "Photon", None))
        self.label_27.setText(_translate("MainWindow", "z", None))
        self.label_30.setText(_translate("MainWindow", "Loc. accuracy", None))
        self.groupBox_storm_config_display.setTitle(_translate("MainWindow", "Uniform STORM dot display", None))
        self.label_14.setText(_translate("MainWindow", "STORM dot size (nm)", None))
        self.pushButton_apply_storm_config.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget_storm_tabs.setTabText(self.tabWidget_storm_tabs.indexOf(self.tab_2), _translate("MainWindow", "Config", None))
        self.groupBox_storm_filter_z.setTitle(_translate("MainWindow", "Z filter", None))
        self.label.setText(_translate("MainWindow", "From", None))
        self.label_2.setText(_translate("MainWindow", "To", None))
        self.groupBox_storm_filter_photon.setTitle(_translate("MainWindow", "Photon filter", None))
        self.label_3.setText(_translate("MainWindow", "From", None))
        self.label_7.setText(_translate("MainWindow", "To", None))
        self.groupBox_storm_filter_frame.setTitle(_translate("MainWindow", "Frame filter", None))
        self.label_9.setText(_translate("MainWindow", "From", None))
        self.label_11.setText(_translate("MainWindow", "To", None))
        self.groupBox_storm_filter_ROI.setTitle(_translate("MainWindow", "ROI filter", None))
        self.groupBox_storm_filter_localdensity.setTitle(_translate("MainWindow", "Local density filter", None))
        self.label_8.setText(_translate("MainWindow", "Radius [nm]", None))
        self.label_10.setText(_translate("MainWindow", "Min number of neighbors", None))
        self.pushButton_apply_storm_filters.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget_storm_tabs.setTabText(self.tabWidget_storm_tabs.indexOf(self.tab_6), _translate("MainWindow", "Filtering", None))
        self.pushButton_unselect_roi.setText(_translate("MainWindow", "Select none", None))
        self.pushButton_delete_roi.setText(_translate("MainWindow", "Delete selected", None))
        self.tabWidget_storm_tabs.setTabText(self.tabWidget_storm_tabs.indexOf(self.tab_7), _translate("MainWindow", "ROIs", None))
        self.groupBox_confocal_top_controls.setTitle(_translate("MainWindow", "Confocal images", None))
        self.pushButton_open_confocal.setText(_translate("MainWindow", "Open files...", None))
        self.pushButton_close_all_confocal.setText(_translate("MainWindow", "Close files", None))
        self.pushButton_show_confocal.setText(_translate("MainWindow", "Show selected", None))
        self.pushButton_unload_confocal.setText(_translate("MainWindow", "Unload selected", None))
        self.pushButton_close_confocal.setText(_translate("MainWindow", "Close selected", None))
        self.tabWidget_confocal_tabs.setTabText(self.tabWidget_confocal_tabs.indexOf(self.tab_3), _translate("MainWindow", "Select", None))
        self.groupBox_confocal_config_resize.setTitle(_translate("MainWindow", "Resize interpolation mode", None))
        self.radioButton_confocal_config_resize_square.setText(_translate("MainWindow", "Square", None))
        self.radioButton_confocal_config_resize_cubic.setText(_translate("MainWindow", "Cubic", None))
        self.radioButton_confocal_config_resize_nearest.setText(_translate("MainWindow", "Nearest neighbors", None))
        self.radioButton_confocal_config_resize_bilinear.setText(_translate("MainWindow", "Bilinear", None))
        self.groupBox_confocal_config_calibration.setTitle(_translate("MainWindow", "Calibration", None))
        self.label_4.setText(_translate("MainWindow", "Px [µm/pixel]", None))
        self.pushButton_apply_confocal_config.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget_confocal_tabs.setTabText(self.tabWidget_confocal_tabs.indexOf(self.tab_4), _translate("MainWindow", "Config", None))
        self.groupBox_confocal_display_appear.setTitle(_translate("MainWindow", "Appearance", None))
        self.label_6.setText(_translate("MainWindow", "Transparency", None))
        self.label_5.setText(_translate("MainWindow", "Z position", None))
        self.groupBox_confocal_display_offset.setTitle(_translate("MainWindow", "Position offset (nm)", None))
        self.label_12.setText(_translate("MainWindow", "x", None))
        self.label_13.setText(_translate("MainWindow", "y", None))
        self.pushButton_apply_confocal_display.setText(_translate("MainWindow", "Apply", None))
        self.tabWidget_confocal_tabs.setTabText(self.tabWidget_confocal_tabs.indexOf(self.tab_5), _translate("MainWindow", "Display", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuSTORMView.setTitle(_translate("MainWindow", "STORM tools", None))
        self.menuTools_2.setTitle(_translate("MainWindow", "Tools", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Plot", None))
        self.groupBox_storm_bottom_controls.setTitle(_translate("MainWindow", "STORM image", None))
        self.checkBox_storm_channel1.setText(_translate("MainWindow", "Ch2", None))
        self.checkBox_storm_channel3.setText(_translate("MainWindow", "Ch4", None))
        self.checkBox_storm_channel0.setText(_translate("MainWindow", "Ch1", None))
        self.checkBox_storm_channel2.setText(_translate("MainWindow", "Ch3", None))
        self.comboBox_storm_channel1_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_storm_channel1_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_storm_channel1_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_storm_channel1_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_storm_channel1_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_storm_channel1_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.comboBox_storm_channel0_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_storm_channel0_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_storm_channel0_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_storm_channel0_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_storm_channel0_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_storm_channel0_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.comboBox_storm_channel2_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_storm_channel2_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_storm_channel2_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_storm_channel2_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_storm_channel2_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_storm_channel2_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.comboBox_storm_channel3_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_storm_channel3_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_storm_channel3_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_storm_channel3_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_storm_channel3_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_storm_channel3_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.label_storm_channel0_info.setText(_translate("MainWindow", "-", None))
        self.label_storm_channel1_info.setText(_translate("MainWindow", "-", None))
        self.label_storm_channel2_info.setText(_translate("MainWindow", "-", None))
        self.label_storm_channel3_info.setText(_translate("MainWindow", "-", None))
        self.groupBox_confocal_bottom_controls.setTitle(_translate("MainWindow", "Confocal image", None))
        self.checkBox_confocal_channel3.setText(_translate("MainWindow", "Ch4", None))
        self.checkBox_confocal_channel2.setText(_translate("MainWindow", "Ch3", None))
        self.comboBox_confocal_channel2_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_confocal_channel2_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_confocal_channel2_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_confocal_channel2_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_confocal_channel2_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_confocal_channel2_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.checkBox_confocal_channel1.setText(_translate("MainWindow", "Ch2", None))
        self.checkBox_confocal_channel0.setText(_translate("MainWindow", "Ch1", None))
        self.comboBox_confocal_channel3_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_confocal_channel3_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_confocal_channel3_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_confocal_channel3_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_confocal_channel3_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_confocal_channel3_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.comboBox_confocal_channel0_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_confocal_channel0_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_confocal_channel0_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_confocal_channel0_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_confocal_channel0_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_confocal_channel0_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.comboBox_confocal_channel1_color.setItemText(0, _translate("MainWindow", "red", None))
        self.comboBox_confocal_channel1_color.setItemText(1, _translate("MainWindow", "green", None))
        self.comboBox_confocal_channel1_color.setItemText(2, _translate("MainWindow", "blue", None))
        self.comboBox_confocal_channel1_color.setItemText(3, _translate("MainWindow", "cyan", None))
        self.comboBox_confocal_channel1_color.setItemText(4, _translate("MainWindow", "magenta", None))
        self.comboBox_confocal_channel1_color.setItemText(5, _translate("MainWindow", "yellow", None))
        self.label_confocal_info.setText(_translate("MainWindow", "-", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3", None))
        self.actionActiveContour_selector.setText(_translate("MainWindow", "Active contour selecting", None))
        self.actionActiveContour_selector.setToolTip(_translate("MainWindow", "Active contour selecting (STORM)", None))
        self.actionActiveContour_selector.setShortcut(_translate("MainWindow", "4", None))
        self.actionLUT_changer.setText(_translate("MainWindow", "LUT settings", None))
        self.actionLUT_changer.setToolTip(_translate("MainWindow", "LUT settings", None))
        self.actionLUT_changer.setShortcut(_translate("MainWindow", "L", None))
        self.actionAnalysis.setText(_translate("MainWindow", "Analysis runner", None))
        self.actionAnalysis.setShortcut(_translate("MainWindow", "A", None))
        self.actionVividSTORM_help.setText(_translate("MainWindow", "VividSTORM help", None))
        self.actionVividSTORM_help.setShortcut(_translate("MainWindow", "F1", None))
        self.actionAbout_VividSTORM.setText(_translate("MainWindow", "About VividSTORM", None))
        self.actionAbout_VividSTORM.setShortcut(_translate("MainWindow", "F2", None))
        self.actionDots.setText(_translate("MainWindow", "Dots view", None))
        self.actionDots.setToolTip(_translate("MainWindow", "Dots view (STORM)", None))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian view", None))
        self.actionGaussian.setToolTip(_translate("MainWindow", "Gaussian view (STORM)", None))
        self.action3D.setText(_translate("MainWindow", "3D view", None))
        self.action3D.setToolTip(_translate("MainWindow", "3D view (STORM)", None))
        self.action3D.setShortcut(_translate("MainWindow", "0", None))
        self.actionShow_1_m_scale.setText(_translate("MainWindow", "Show  scale", None))
        self.actionShow_1_m_scale.setShortcut(_translate("MainWindow", "S", None))
        self.actionOpen_STORM_files.setText(_translate("MainWindow", "Open STORM files...", None))
        self.actionOpen_STORM_files.setToolTip(_translate("MainWindow", "Open STORM image files", None))
        self.actionOpen_STORM_files.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionOpen_Confocal_files.setText(_translate("MainWindow", "Open Confocal files...", None))
        self.actionOpen_Confocal_files.setToolTip(_translate("MainWindow", "Open Confocal image files", None))
        self.actionOpen_Confocal_files.setShortcut(_translate("MainWindow", "Ctrl+Shift+O", None))
        self.actionExport_As_Image.setText(_translate("MainWindow", "Export as Image file...", None))
        self.actionExport_As_Image.setIconText(_translate("MainWindow", "Export as image", None))
        self.actionExport_As_Image.setToolTip(_translate("MainWindow", "Export as Image file", None))
        self.actionClose_STORM_files.setText(_translate("MainWindow", "Close STORM files", None))
        self.actionClose_STORM_files.setToolTip(_translate("MainWindow", "Close STORM files", None))
        self.actionClose_STORM_files.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionClose_Confocal_files.setText(_translate("MainWindow", "Close Confocal files", None))
        self.actionClose_Confocal_files.setToolTip(_translate("MainWindow", "Close Confocal files", None))
        self.actionClose_Confocal_files.setShortcut(_translate("MainWindow", "Ctrl+Shift+X", None))
        self.actionSet_working_directory.setText(_translate("MainWindow", "Set working directory...", None))
        self.actionSet_working_directory.setShortcut(_translate("MainWindow", "Ctrl+D", None))
        self.actionPositioning_tool.setText(_translate("MainWindow", "Positioning", None))
        self.actionPositioning_tool.setToolTip(_translate("MainWindow", "Positioning tool (Confocal)", None))
        self.actionFreehand_selecting.setText(_translate("MainWindow", "Freehand ROI select", None))
        self.actionFreehand_selecting.setToolTip(_translate("MainWindow", "Freehand ROI select (STORM)", None))
        self.actionFreehand_selecting.setShortcut(_translate("MainWindow", "1", None))
        self.actionEllipse_ROI_selecting.setText(_translate("MainWindow", "Ellipse ROI select", None))
        self.actionEllipse_ROI_selecting.setToolTip(_translate("MainWindow", "Ellipse ROI select (STORM)", None))
        self.actionEllipse_ROI_selecting.setShortcut(_translate("MainWindow", "2", None))
        self.actionDragging_mode.setText(_translate("MainWindow", "Dragging mode", None))
        self.actionDragging_mode.setToolTip(_translate("MainWindow", "Dragging mode switch (Plot / Confocal)", None))
        self.actionDragging_mode.setShortcut(_translate("MainWindow", "Space", None))
        self.actionCircle_ROI_selecting.setText(_translate("MainWindow", "Circle ROI select", None))
        self.actionCircle_ROI_selecting.setToolTip(_translate("MainWindow", "Circle ROI select (STORM)", None))
        self.actionCircle_ROI_selecting.setShortcut(_translate("MainWindow", "3", None))
        self.actionImage_Registration.setText(_translate("MainWindow", "Image Registration", None))
        self.actionImage_Registration.setToolTip(_translate("MainWindow", "Register STORM and confocal images", None))
        self.actionImage_Registration.setShortcut(_translate("MainWindow", "I", None))
        self.actionJoin_Result_files_in_a_folder.setText(_translate("MainWindow", "Join Result files in a folder...", None))
        self.actionJoin_ROI_attribute_files_in_a_folder.setText(_translate("MainWindow", "Join ROI attribute files in a folder...", None))
        self.actionDelete_ROI_selector.setText(_translate("MainWindow", "Delete ROI", None))
        self.actionDelete_ROI_selector.setShortcut(_translate("MainWindow", "R", None))

import main_resources_rc
